### ISSUE TITLE
Allow MHV premium to log in as LOA3 for SiS

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10264]
MHV Premium accounts are currently logged in as LOA1, we should inspect the relevant values and allow them to log in as an LOA3 user

**Comment by nsoutouras** [comment]
Waiting on some info from ID.me.

**Comment by joeniquette** [comment]
I tested this with MHV staging using vets250 and the user is able to login now without being forced to verify through idme. This task is confirmed to be good to go for MHV users.
