### ISSUE TITLE
Add proper error codes for MPI data errors in Sign in Service

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10301]
With another ticket we block auth based off certain MPI malformed ids, but they only respond with text errors. We should also respond with an error code so frontend can use these errors

**Comment by joeniquette** [comment]
Use this document as a source of possible errors from MPI: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/Errors/MPI/external.md
