### ISSUE TITLE
need confirmation number to give to frontend

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-api#106]
i'm thinking about adding a uuid column to education_benefits_claims and using that for the confirmation number, thoughts @markolson?

**Comment by markolson** [comment]
Let's just use the EducationBenefitsClaim id.

**Comment by markolson** [comment]
I'm going to assign this to myself as I'm working in that area right now as well.

**Comment by akainic** [comment]
We're going to use the id from our database table.
