### ISSUE TITLE
Route users with specific attributes and MPI record correctly within Sign in Service authentication

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10805]
When authenticating with Sign in Service, we update the corresponding MPI record for a user with their credential data. There are some cases where this doesn’t make sense, so we should block the update (and potentially even block the authentication). Cases are below:

- User logged in with loa1/ial1 -> should not update MPI record
- User logged in with loa3 MHV -> should not update MPI record (no user data to update, they only have an ICN)
- User logged in with loa3 dslogon -> should update MPI record
- User logged in with loa3 idme -> should update MPI record
- User logged in with ial2 logingov -> should update mpi record
- User missing first/last name, birth_date, or ssn in credential -> Should not update mpi record (credential information is incomplete)
- User first name, last name, birth_date, ssn does not match MPI, but this is because MPI attribute is nil -> should update MPI record
- User first name does not match existing MPI attribute -> Log ‘credential name difference’, update MPI record
- User last name does not match existing MPI attribute -> Log ‘credential name difference’, update MPI record
- User birth_date does not match existing MPI attribute -> log ‘credential name difference’, block authentication (do not update MPI record)
- User ssn does not match existing MPI attribute -> log ‘credential name difference’, block authentication (do not update MPI record)

**Comment by joeniquette** [comment]
We should check with Danny about how to handle this. I want to know more about why and when these come up in regards to MPI. In theory should not be possible, but in some cases these I believe are OK. Such as someone got married and their last name has changed:

- User first name does not match existing MPI attribute -> Log ‘credential name difference’, update MPI record
- User last name does not match existing MPI attribute -> Log ‘credential name difference’, update MPI record
- User birth_date does not match existing MPI attribute -> log ‘credential name difference’, block authentication (do not update MPI record)
- User ssn does not match existing MPI attribute -> log ‘credential name difference’, block authentication (do not update MPI record)

**Comment by joeniquette** [comment]
What about:
- address is different
- email is different

**Comment by bramleyjl** [comment]
| IAL/LoA - CSP     | Authenticate? | Update MPI? |
| ----------- | ----------- | ----------- |
| IAL1      | Yes       | No |
| IAL2 - Login.gov  | Yes        | Yes |
| LoA1      | Yes       | No |
| LoA3 - MHV  | Yes        | No |
| LoA3 - DSLogon  | Yes        | Yes |
| LoA3 - ID.me  | Yes        | Yes |

--------------------------

| Credential | Context | Authenticate? | Update MPI? |
| ----------- | ----------- | ----------- | ----------- |
| Any | CSP credential value is missing  | Yes | No |
| Any | MPI credential value is missing | Yes | Yes |
| `first_name` | MPI profile `given_names.first` doesn't match | Yes | Yes, log `Credential first_name difference` |
| `last_name` | MPI profile `family_name` doesn't match | Yes | Yes, log `Credential last_name difference` |
| `birth_date` | MPI profile `birth_date` doesn't match | No | No, log `Credential birth_date difference` |
| `ssn` | MPI profile `ssn` doesn't match | No | No, log `Credential ssn difference` |


Todo:
* address doesn't match
* email doesn't match
* multiple attributes don't match

**Comment by joeniquette** [comment]
@joeniquette create DD metrics for these errors

**Comment by joeniquette** [comment]
@joeniquette to update: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Design%20Documents/UserAttribute_Rules.md

**Comment by joeniquette** [comment]
Update attribute rules in documentation: https://github.com/department-of-veterans-affairs/va.gov-team/pull/48554

**Comment by joeniquette** [comment]
![Screen Shot 2022-10-20 at 21.59.38.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/d3ddd99c-fe30-4af2-bde2-4ecced465078) metrics added to DD

**Comment by joeniquette** [comment]
Document completed, closing ticket
