### ISSUE TITLE
Add email to MPI add_person or update_person calls

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10848]
When Sign in Service calls MPI and updates the credential correlation record, or adds a new MPI record altogether, that gives us an ability to send them the user's credential email.

**Comment by bosawt** [comment]
MPI service itself doesn't seem to have a robust enough implementation of email to actually do comparisons.  However, we can still send email to MPI during updates and add records to help them populate the field

**Comment by bosawt** [comment]
PR is ready, but I'm trying to find out if the result actually worked (as we don't have an easy way to tell on our end, we need confirmation from Danny Reed or someone else who directly works with MPI)

**Comment by joeniquette** [comment]
Trevor to pull correlation record to see if they have an email

**Comment by alyssagallion** [comment]
Waiting on Danny Reed.
