### ISSUE TITLE
Create script to automatically update existing mock data users with newest MPI records

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10928]
Many mock data records are out of date, and there's no easy way to update and maintain with MPI. We should create a script that developers can either use to easily update a mocked record, or automatically update these records

**Comment by alyssagallion** [comment]
Merged.
Next step, automate process (backlog ticket here): https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/48581
Closing.
