### ISSUE TITLE
Fix Sign in Service undefined method error

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10951]
https://sentry.vfs.va.gov/organizations/vsp/issues/160316/?environment=production&project=3&query=is%3Aunresolved+signincontroller&statsPeriod=24h

In sign in service, if MPI or credential has missing attributes, we will unexpectedly run into an 'undefined method error', we should deal with this correctly, which is:

- MPI missing attributes: don't raise unexpected error, but continue (credential should fill in these missing attributes)
- Credential missing attributes: don't raise unexpected error, but we should probably block auth on certain conditions (missing SSN for sure, maybe missing b-date and name as well)

**Comment by alyssagallion** [comment]
Being resolved in this ticket:

https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/10951
