### ISSUE TITLE
Add user_account to terms_and_conditions model

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#11196]
TermsAndConditions model currently is tied to `user_uuid`, which is backed by idme_uuid or logingov_uuid. Instead, this should be backed by UserAccount, and the first step is to add this as an association on the model

**Comment by alyssagallion** [comment]
Ongoing tech debt.

**Comment by bosawt** [comment]
Can confirm records are being created with `user_accounts` on them
