### ISSUE TITLE
Remove SessionActivity model and table

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#11193]
SessionActivity model is currently unused, there are no records in the database, and nothing is able to currently call this model. It hasn't been touched in years, and seem like it can be removed

**Comment by alyssagallion** [comment]
Ongoing tech debt.

**Comment by bosawt** [comment]
Confirmed table is dropped:
`irb(main):003:0> ActiveRecord::Base.connection.execute('Select * from session_activities LIMIT 1')
Traceback (most recent call last):
        1: from (irb):3
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "session_activities" does not exist)
LINE 1: Select * from session_activities LIMIT 1`
