### ISSUE TITLE
Remove Notifications and DismissedStatusesController

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#11306]
Notifications controller hasn't created a Notifications record in about a year and a half, and has had no usage in the past 30 days:
https://vagov.ddog-gov.com/logs?query=%22NotificationsController%22&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1667697031192&to_ts=1670289031192&live=true

DismissedStatusesController additionally has not had any usage in the past 30 days:
https://vagov.ddog-gov.com/logs?query=%22DismissedStatusesController%22&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1667697031192&to_ts=1670289031192&live=true

So I think it's safe to remove these

**Comment by alyssagallion** [comment]
Need to follow up with front end to verify that it isn't being used by them.
