### ISSUE TITLE
Refactor MPI for more direct querying

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#11329]
MPI currently requires a `UserIdentity` to query, and there are enough users of the service that it doesn't really make sense anymore to tie MPI querying to a `User` or `UserIdentity`, so we should refactor it so that it takes directly the fields we want to query off of it

**Comment by bosawt** [comment]
This ticket will focus on the `add_person_implicit_search` call. I'll make tickets for the other MPI calls

**Comment by alyssagallion** [comment]
Pending back-end refactoring.
