### ISSUE TITLE
Create logout redirect proxy for Sign in Service login.gov users

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#11974]
When a user authenticates with login.gov on Sign in Service, and they log out, they first need to redirect to login.gov logout, then redirect back to their chosen site. This will only work if we set up a redirect proxy with login.gov, make it so login.gov redirects to the chosen proxy, and then redirect appropriately to the logout redirect set up in the Client Config

**Comment by mjconw3** [comment]
@bosawt ...Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed.
