### ISSUE TITLE
Tech Discovery - Common API Migration

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/vets-api#12052]
Janet Coutinho [posted in Slack](https://dsva.slack.com/archives/C02CQP3RFFX/p1676574262007819) about "Common API" endpoints that need to be migrated?

Is there engineering work that needs to be done on these?

She identified Next Steps in Slack:
> 1. Verify that VA.gov can either stop calling wss-common-services-web-11.6/rest/vsoSearch/11.6/getCurrentInfo or replace it with a Lighthouse API.
> 2. Work with VA.gov to combine the two EVSS disability calls on the disability page into a single call to the Lighthouse veteran_verification/v2/disability_rating.
> 3. Work with VA.gov to change the form526 wizard to use the Lighthouse veteran_verification/v2/disability_rating.

Acceptance Criteria:
- [ ] Identify if any common API endpoints are being called from 526 and from where
- [ ] Identify which LH endpoint replaces each call that still needs to be built

**Comment by navaeddie** [comment]
The three "Next Steps" identified in the the Slack message identify 3 different steps to take, but two of them seem to apply to the same endpoint URL. And it's not clear if the Next Steps she identified must be completed before EVSS is shut down.

**getCurrentInfo**
1.  Verify that [VA.gov](http://va.gov/) can either stop calling wss-common-services-web-11.6/rest/vsoSearch/11.6/getCurrentInfo or replace it with a Lighthouse API.
	1. EVSS metrics report 6,901 hits in a month
	2. Categorized under "VSO search" in EVSS Metrics. What is that? Someone else covering it?


**disability_rating**
2.  Work with [VA.gov](http://va.gov/) to combine the two EVSS disability calls on the disability page into a single call to the Lighthouse veteran_verification/v2/disability_rating.
3.  Work with [VA.gov](http://va.gov/) to change the form526 wizard to use the Lighthouse veteran_verification/v2/disability_rating.
	1. Robin said it's not currently being used
	2. My reading of the code confirms Robin's suggestion
	3. I don't see it listed in EVSS metrics of hit within 90 day period

**Comment by navaeddie** [comment]
Janet Coutinho noted in a subsequent message about the "getCurrentInfo" endpoint

> This API is used when users apply for the Rogers STEM Scholarship on VA.gov
> It might be possible to be replace this API with the Lighthouse PowerOfAttorney operation in the Claims API. However, as far as I can tell, VA.gov only uses one field in the vsoSearch response and its value is always “userPoaInfoAvailable=true”, so they might not need this API.

**Comment by RakshindaAslam** [comment]
Outcome of this discovery ticket - No migration work required for 526ez flow for Common Services API endpoint.
