### ISSUE TITLE
Update Sign in Service `/callback` redirect so that it returns with script instead of a redirect

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#12148]
When a user authenticates with a credential provider, upon successfully authenticating, the Sign in Service `/callback` route will get called. This route then redirects to the VA.gov frontend upon completion. This process works fine with the VA.gov frontend, because VA.gov is specifically set in the CORS security policy. When Sign in Service is integrated with other clients, however, the redirect will be expected to be performed on other sites. In order to do this, we potentially have to do a 'hack', where the `/callback` route returns a 200 response, with a small javascript page that then redirects to the appropriate site. We already have examples of this in the `/authorize` and `/logingov_logout_proxy` functions in Sign in Service

**Comment by mjconw3** [comment]
@bosawt ...Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed. Moving forward we will be adding acceptance criteria to all tickets to make review easier (not a problem for now while you all were managing your own tickets)
