### ISSUE TITLE
Ensure No External Requests in Initializers

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/vets-api#123]
Normally webmock would catch any external requests, but if they occur in an initializer prior to `WebMock.disable_net_connect!` they will actually be made.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/saml_settings.rb is one such example. 

If the IDP is down, this will result in a build breaking or test environments failing, we need to have a more robust mechanism for handling these issues and we should always make sure they happen at an application runtime level, not at initialization.

One solution would be to move the saml_settings into a service class that is invoked at controller level, and have it be redis backed -- the metadata would be loaded from redis first, if it is not available it will make the request and cache it to redis for future requests. We should set the timeout window to something short -- like 5-10 seconds, and we should rescue exception with our own custom exception class to ensure that the error is logged, JSON is returned informing of the issue. In this case, it would likely be a 500 level error.

Another solution would be to hardcode the metadata, if this is not subject to change that is. We could then just load it as an ENV var.

**Comment by robbiethegeek** [comment]
@ayaleloehr I assigned this to @saneshark can you help prioritize this against other work.  Not super high priority but will effect all the devs if ID.me is down.

**Comment by robbiethegeek** [comment]
@ayaleloehr @saneshark pulled this to @omgitsbillryan , he will do the work and then add @saneshark as the reviewer.

**Comment by saneshark** [comment]
This is helpful. I am not sure when I would have had a chance to get to it, plus @omgitsbillryan probably can answer the question of wether or not we can just hardcode the metadata similar to what was done for MVI WSDL files. In a way, this seems like a similar concept. We only want it initialized once, so makes sense to be in initializer, but if it is not subject to frequent enough change, then maybe we just load it into memory and set a constant without making a request? Redis would work too of course (but then it would be getting fetched either from Redis or via get request every time the web server forks off for an incoming request).

**Comment by omgitsbillryan** [comment]
I don't think it's typical that IDP metadata changes very often, but I do like the idea of fetching it with an external call.  In the event that something does change, a server restart will be all that's necessary to re-fetch it.  I'm not a fan of a Redis-backed-service since we will be reading these `SAML:SETTINGS` very frequently and it's faster to do so from local memory than from Redis.

I don't like the idea of an external call inside an initializer, but I think it may be justified in this case - though we probably want to wrap in a begin-rescue so that if it fails, the app will still run.

Then again, I've been flip flopping in my head on this one for most of this moring :-P

**Comment by omgitsbillryan** [comment]
@saneshark very cool stuff, I think this will serve our purposes.

**Comment by saneshark** [comment]
@omgitsbillryan possibly consider putting it in lib instead instead of initializers since it is a class. That way you'll be forced to write specs for it that at a unit level and can mock up something with webmock that gets served up both for your unit spec and used by controllers as a helper. At some point were going to need a helper that stubs authentication, currently everyone's controllers are just skipping the authenticate before_filter

**Comment by omgitsbillryan** [comment]
@saneshark Review started #223
