### ISSUE TITLE
Remove DownTime checker Sidekiq middleware

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#12301]
The 'DownTime' checker class is a bizarre bit of Sidekiq middleware that prevents BGS jobs from being retried between 2:00 AM and 10:00 AM UTC. It doesn't seem to serve an appropriate purpose, as we already have retry ability for Sidekiq, so we should remove this

**Comment by bosawt** [comment]
This is in prod and appears to have dramatically reduced errors in the 686c form by a dramatic amount

**Comment by mjconw3** [comment]
@bosawt Just took a look at this...looks good. Going to close
