### ISSUE TITLE
Investigate Datadog metrics anomalies 

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/vets-api#12498]
## Summary
We have discovered that metrics pre EKS are inflated and the current metrics are correct. This is because pre EKS metrics we're coming in as type `count` and new metrics with the same name are coming in as `rate; interval:10`
https://dsva.slack.com/archives/C04LW2P19M0/p1682545553327789

## Possible Solutions
- Reach out to Datadog to see if they can fix past metrics - @joeniquette 
- See if we can divide past metrics by 10 on our graphs to keep historical values accurate

**Comment by joeniquette** [comment]
This is complete, closing.
