### ISSUE TITLE
Nested facility service data

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#126]
@patrickvinograd VHA data (which is what we have available via the VA API right now) has services available at facilities. these services look flat in the data returned from the VA's API, however they are actually nested in that some of the services are major categories (service level 1 = SL1) and some are minor categories (Service level 2 = SL2) within major categories. An example of this is that DiagnosticServices is an SL1 while ImagingAndRadiology and LabServices are SL2's that fit under DiagnosticServices.

I believe that instead of returning something like (this is just a subset of what's returned for a facility):
```
{
    "DiagnosticServices": "YES",
    "ImagingAndRadiology": "YES",
    "LabServices": "NO",
}
```
We should do something like:
```
{
    "DiagnosticServices": {
        "ImagingAndRadiology": true,
    }
}
```

Two changes here: 
(1) is that it ImagingAndRadiology is nested under DiagnosticServices, so the front end knows they are associated
(2) is that only the services that are available at the facility show up, rather than having a whole lot of "NO"s in there.  
Note, the "true" there at the end still feels weird to me and I'm sure there is a better way of doing, but I just wanted to get this concept overall out there first.

**Comment by ayaleloehr** [comment]
You're probably also saying, well which services are nested under what?!  Here is a list: 

```
Audiology
ComplementaryAlternativeMed
DentalServices
DiagnosticServices
	ImagingAndRadiology
	LabServices
EmergencyDept
EyeCare
MentalHealthCare
	OutpatientMHCare
	OutpatientSpecMHCare
	VocationalAssistance
OutpatientMedicalSpecialty
	AllergyAndImmunology
	CardiologyCareServices
	DermatologyCareServices
	Diabetes
	Dialysis
	Endocrinology
	Gastroenterology
	Hematology
	InfectiousDisease
	InternalMedicine
	Nephrology
	Neurology
	Oncology
	PulmonaryRespiratoryDisease
	Rheumatology
	SleepMedicine
OutpatientSurgicalSpecialty
	CardiacSurgery
	ColoRectalSurgery
	ENT
	GeneralSurgery
	Gynecology
	Neurosurgery
	Orthopedics
	PainManagement
	PlasticSurgery
	Podiatry
	ThoracicSurgery
	Urology
	VascularSurgery
PrimaryCare
Rehabilitation
UrgentCare
WellnessAndPreventativeCare
```

**Comment by bshyong** [comment]
re: 1) In the front-end, it would be nice to have the keys nested and the nesting logic built into the API. It's probably better to have the service hierarchy in the backend instead of frontend.

re: 2), only including services that are available saves us from having to iterate over the entire response. As an added bonus, we could use the value to store a formatted display name, ie 

```json
"MentalHealthCare": {
      OutpatientMHCare: "Outpatient Mental Health Care"
}
```

**Comment by patrickvinograd** [comment]
Yes, absolutely on both returning the hierarchy and only including the present services. My suggestion is something like this:
```
...
"Services": {
  "PrimaryCare": [],
  "Rehabilitation": [],
  "MentalHealthCare": ["OutpatientMHCare", "OutpatientSpecMHCare"]
}
...
```
I.e. SL1 services are indicated by presence as keys in the overall "Services" dict. SL2 services are indicated by presence in the list that you get back from their parent SL1 key. SL1 services that don't have any sub-services have an empty list, but are still available as a top-level service. 

It's a little awkward mixing dicts and lists, but it avoids the redundant "true" values for the SL2 services. And while I like the idea of the backend owning/returning the display names, I don't want to repeat that information on each and every record. I'd rather have a separate metadata endpoint where we can serve the hierarchy info statically; frontend apps can retrieve it once and cache it.

**Comment by patrickvinograd** [comment]
Representing the L1 services as keys in a dict makes things awkward because the keys get treated as keys from the JSON API perspective and get munged by Olive Branch, but the values do not. So now proposing to make the services a big nested list so it just gets treated as data:
```
[
  ["Audiology",[]],
  ["DentalServices",[]],
  ["DiagnosticServices",["ImagingAndRadiology"]],
  ["EyeCare",[]],
  ["MentalHealthCare",["OutpatientMHCare","OutpatientSpecMHCare","VocationalAssistance"]],
  ["OutpatientSurgicalSpecialty",["Podiatry"]],
  ["PrimaryCare",[]],
  ["Rehabilitation",[]],
  ["WellnessAndPreventativeCare",[]]
]
```
Overall list of services is a list of tuples, first element being an SL1 service, second element being a list of SL2 services (or an empty list).

**Comment by carlmjohnson** [comment]
What about something like this:

```json
[
	{
		"L1": "Audiology",
		"L2": []
	},
	{
		"L1": "DentalServices",
		"L2": []
	},
	{
		"L1": "DiagnosticServices",
		"L2": [
			"ImagingAndRadiology"
		]
	},
	{
		"L1": "EyeCare",
		"L2": []
	},
	{
		"L1": "MentalHealthCare",
		"L2": [
			"OutpatientMHCare",
			"OutpatientSpecMHCare",
			"VocationalAssistance"
		]
	},
	{
		"L1": "OutpatientSurgicalSpecialty",
		"L2": [
			"Podiatry"
		]
	},
	{
		"L1": "PrimaryCare",
		"L2": []
	},
	{
		"L1": "Rehabilitation",
		"L2": []
	},
	{
		"L1": "WellnessAndPreventativeCare",
		"L2": []
	}
]
```

**Comment by patrickvinograd** [comment]
@carlmjohnson Yeah, I like that better, having the L1/L2 keys gives some indication of the semantics.

**Comment by bshyong** [comment]
^ that structure LGTM

**Comment by patrickvinograd** [comment]
Works well with olive branch so I'm going to say that's decided. See #134 for full record format description.
