### ISSUE TITLE
Define facility locator choice act data format

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#140]
See https://github.com/department-of-veterans-affairs/kudos-team/blob/master/FacilityLocator/Facility%20Data%20Samples.md for a description of the underlying data. 
See #134 for related discussion of VA health facility data.

Like #134 we need to define the output of REST queries for choice act (non-VA provider) data. 

Whereas the VA facility GIS data returns facilities (i.e. hospitals/clinic) and their services, the Choice act GIS data returns individual providers (i.e doctors). The data is de-normalized, so a given doctor may have multiple records for each of the specialty they provide at a location, and may have multiple records for each of the locations that they work from. So we need to do some level of aggregation - at least combining all of a doctor's specialties at a given location, and possibly combining all providers at a given location so we can display a map pin. 

It does not appear that there is any stable unique identifier that lets us aggregate all the providers and services at a single location (i.e. at a map pin). The UniqueProviderCode identifies a doctor but may give multiple locations. So it may not make sense to provide a "get single record by ID" API operation for getting details - all operations on this may effectively be queries by lat/long. But we need to analyze the data to see how accurate the lat/long data is.

**Comment by ayaleloehr** [comment]
Thanks for bringing this up!; very interesting that providers can have both multiple specialities at the same location and also can have multiple locations.  

First off, a couple thoughts on if we don't do any aggregation on the backend...the way I have usually seen multiple points with at the same location implemented on the frontend is with "exploding" or "spidering" points, which look like a normal point at first then when clicked change to something like: 

<img width="162" alt="screen shot 2015-06-03 at 9 02 51 pm" src="https://cloud.githubusercontent.com/assets/4719765/18729196/cc91e10c-801e-11e6-9a87-2b9f4602b593.png">

But that's usually done with [MarkerClusters](https://github.com/Leaflet/Leaflet.markercluster), and I don't think we actually want to cluster all our markers. In other words I don't know how to have our markers generally look as they do now but when on top of each other and clicked, have that point then spider to show a group of markers.  

The [Choice Act Locator](http://www.va.gov/opa/apps/locator/), which is the web app currently using the same API as we are for this data, doesn't aggregate points on the backend but rather has the concept of "next" inside the modal, so as you can see in this image, there are 9 points on top of each other and you can forward and back on the modal to see all of them: 

![screen shot 2016-09-21 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/4719765/18729274/2e85098e-801f-11e6-876b-55c787973e3b.png)

The Choice Act Locator also doesn't have a details page, so as you say, all queries are by lat/long  and (optional) speciality.  But none of that answered your question, so let me try to get back to that...

Are you thinking this aggregation needs to happen on both the map view and details view, or just one of those?  I think one approach could be to have the map view do an aggregation like "if the UniqueProviderCode is the same at the exact same lat/long (or within .0001 or something if they aren't exact), only put the first of those records returned in the JSON". That would eliminate having the same provider at the same location multiple times.

And then if we want a detail page for choice act data, we could have that do a query by UniqueProviderCode and return the different specialities at the different locations (if there are multiple). This may need to be a different looking details page than the non-choice act data now that the json response would be different, but the underlying data is different, so not sure if there is any way around having a different response format (or at a minimum fewer keys) anyways. And on the choice act details page we would definitely want some content like "To schedule a Veterans Choice Program appointment you must call 866-606-8198. 
Please do not contact your provider directly," so having a separate choice act details page than VA facilities details page seems reasonable actually. 

Finally, I would say hold off on actually implementing any of this yet. Let's get the non-choice-act (AKA VA) data working first and then circle back to this and make some decisions then?

**Comment by patrickvinograd** [comment]
Yes, not implementing yet, just getting the ball rolling. 

I think at a minimum, we should aggregate all the specialties for one provider (for both map marker and detail view), since we can easily represent a list type in our JSON response, we don't want to inherit the unfortunate GIS db representation into our API. 

Then we can decide (later) whether providers at the same location get grouped somehow by the backend, or whether the frontend does this. For detail view, getting by UniqueProvider sounds good, although we'll need to see how the display works out - if we show all available locations, and the first one listed is across town that might be confusing for the user. Maybe we can highlight based on coordinates. 

While I'm not going to implement the API right now, I am going to pull down some bulk data from the endpoint and see what the data accuracy looks like so we know if there are any bumps ahead. Will put a straw-person JSON format here as well.
