### ISSUE TITLE
Replace httpclient with Net::HTTP for EVSS services

### ISSUE THREAD

**Issue by raquelromano-gov** [department-of-veterans-affairs/vets-api#1511]
Pasting @kreek 's suggestion in [1496](https://github.com/department-of-veterans-affairs/vets-api/pull/1496) for how to get around the capitalization issues

---

An alternate solution may be to fix why we use `httpclient` for EVSS in the first place. `Net::HTTP` capitalizes headers, this is a problem for services like EVSS that don’t follow the w3 spec that field names should be case-insensitive. The comment [in this thread](https://github.com/jnunemaker/httparty/issues/406) (right below Carl’s) 😀  describes a `Net::HTTP::ImmutableHeaderKey` class which stops the capitalization occurring without monkey patching `Net::HTTP` for the entire app (I had to add `capitalize!` as well to get it to work):
```ruby
class Net::HTTP::ImmutableHeaderKey
  attr_reader :key

  def initialize(key)
    @key = key
  end

  def downcase
    self
  end

  def capitalize
    self
  end

  def capitalize!
    self
  end

  def split(*)
    [self]
  end

  def hash
    key.hash
  end

  def eql?(other)
    key.eql? other.key.eql?
  end

  def to_s
    def self.to_s
      key
    end
    self
  end
end
```

Then you can create EVSS headers as below:
```ruby
module EVSS
  class AuthHeaders
    def initialize(user)
      @user = user
    end

    def to_h
      @headers ||= {
        Net::HTTP::ImmutableHeaderKey.new('va_eauth_csid') => 'DSLogon',
        Net::HTTP::ImmutableHeaderKey.new('va_eauth_authenticationmethod') => 'DSLogon',
        Net::HTTP::ImmutableHeaderKey.new('va_eauth_pnidtype') => 'SSN',
        # ...
```

In my tests, hitting the EVSS letters service with 100 requests, `Net::HTTP` is much faster than the other clients Faraday supports (need to dig into why):
```
net_http: 63.55 ms
httpclient: 25146.97 ms
patron: 7322.04 ms
```

**Comment by kreek** [comment]
Issue moved to [department-of-veterans-affairs/vets.gov-team #5820](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5820) via [**ZenHub**](https://www.zenhub.com/)
