### ISSUE TITLE
[Rx] PATCH request to refill prescription returns 500.

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-api#163]
While refactoring Rx to make the change to using camelCase when working with the API and doing some quick testing to see if anything broke, I tested refill requests. I don't remember if they're expected to be broken at the moment, but I got an internal server error when I tried one. Info listed below, including time of response in the header.

When I load the page later, the prescriptions I requested refills on are still in either a "pending" or "refill in process" state, so I guess something did take effect server side. Just checking to see if this is expected behavior or if anyone has a explanation for this.

## Request Headers:
```
PATCH /api/v0/prescriptions//13568747/refill HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
origin: http://localhost:3000
Referer: http://localhost:3000/rx
Connection: keep-alive
```

## Response Headers
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Date: Mon, 26 Sep 2016 22:34:09 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 105
Connection: close
access-control-allow-headers: Authorization
Cache-Control: no-cache
X-Git-SHA: 5ce0a67fc80dd02ea010fca0a433d940fbf854e0
X-GitHub-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Request-Id: 8829d4ef-a813-43ef-99e5-2b594018440b
X-Runtime: 1.495591
access-control-allow-credentials: true
Set-Cookie: TS018eb766=01c8917e484bb76fec64a30ed342ba9f1b2e0aea1b999a355c9aca60b934e16fdac77944fb; Max-Age=900; Path=/
```

## Response:
```
{"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":500}]}
```

**Comment by ayaleloehr** [comment]
@U-DON on dev.vets.gov (or connecting to the dev API), the PATCH will not work because that is using the Heroku mock API rather than a real MHV API.  If you test this locally using the staging API instead, it should work. Using the staging API, however, I get a different error, which in this case I believe is expected:

```
{
  "errors": [
    {
      "title": "Operation failed",
      "detail": "Prescription is not refillable",
      "code": "900",
      "status": 400
    }
  ]
}
```
So that prescription just isn't refillable on the staging API. Can you try this request on staging with a prescription that is refillable and let me know if it works?

**Comment by saneshark** [comment]
I'm just chiming in to agree with @ayaleloehr on his comment. Staging will be more of a 'true' test for something like refill which would affect the state of the resource. Please let us know if you encounter any issues other than "Prescription is not refillable," when using staging.

**Comment by U-DON** [comment]
When I tried these requests, they were done locally using the staging API.

**Comment by U-DON** [comment]
@ayaleloehr I do get that error when I run the request on something that is not refillable, but as I mentioned in the opening post, I get the 500 on something that is refillable. But the status of the prescription successfully (?) changes to pending or in process later.

There are only two active prescriptions left I can request a refill on, so I don't want to try it on those yet, unless there's more information we can unearth from doing so.

**Comment by ayaleloehr** [comment]
I can email MHV tonight and get more prescriptions refillable.  We want the ability to make these refillable ourselves (Josh is working on this for end to end testing), but don't have it today unfortunately.

**Comment by ayaleloehr** [comment]
@U-DON sorry for the delay. Prescriptions have now been updated. More are now refillable and some are now on hold and discontinued so that we can test seeing those status types as well. I'm going to assign back to you for you to test if you get a 500 error still. Please close if this seems to be working or post another failing request/response if it continues happening!

**Comment by U-DON** [comment]
I still get an internal server error. I can try running the API locally to see if I can get a more descriptive error out of it.

## Request
```
PATCH /api/v0/prescriptions//13650542/refill HTTP/1.1
Host: localhost:3001
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
origin: http://localhost:3001
Referer: http://localhost:3001/rx
Connection: keep-alive
```

## Response
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Server: nginx/1.10.1
Date: Wed, 05 Oct 2016 15:47:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 105
Connection: close
Cache-Control: no-cache
Vary: Origin
x-content-type-options: nosniff
X-Frame-Options: SAMEORIGIN
X-Git-SHA: 7038b67aacd77c290975f8846ad70fda17867f2f
X-GitHub-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Request-Id: fd53e887-e79f-4e8a-b8ca-ad51cab0905b
X-Runtime: 2.461080
X-XSS-Protection: 1; mode=block
access-control-allow-credentials: true
```
```
{"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":500}]}
```

**Comment by U-DON** [comment]
Never mind, can't seem to do PATCH requests locally for some reason. They keep getting turned into OPTIONS requests. Don't know why that is; on Messaging, POST and DELETE work fine.

**Comment by ayaleloehr** [comment]
Error log is:
```
I, [2016-10-05T15:47:29.452584 #2105] INFO -- : Started PATCH "/v0/prescriptions/13650542/refill" for 152.130.39.81 at 2016-10-05 15:47:29 +0000
I, [2016-10-05T15:47:29.456538 #2105] INFO -- : Processing by V0::PrescriptionsController#refill as JSON
I, [2016-10-05T15:47:29.456598 #2105] INFO -- : Parameters: {"id"=>"13650542"}
E, [2016-10-05T15:47:31.911413 #2105] ERROR -- : 795: unexpected token at 'Successfully submitted to: DAYT29'.
E, [2016-10-05T15:47:31.911661 #2105] ERROR -- : /srv/platform-api/src/lib/rx/client.rb:57:in `rescue in process_response_or_error'
/srv/platform-api/src/lib/rx/client.rb:54:in `process_response_or_error'
/srv/platform-api/src/lib/rx/client.rb:49:in `perform'
/srv/platform-api/src/lib/rx/api/prescriptions.rb:36:in `post_refill_rx'
/srv/platform-api/src/app/controllers/v0/prescriptions_controller.rb:36:in `refill'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/srv/platform-api/src/vendor/bundle/ruby/2.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
```
@saneshark thoughts?

**Comment by saneshark** [comment]
@U-DON can you verify that the count for refill actually changed? It appears as though MHV is returning a normal string instead of a JSON string in the response.body and therefore it's causing a serialization error -- really they should be returning no content and status 200, this is bad design on their part, but I will fix it.

**Comment by saneshark** [comment]
Even if it was `{ status: Successfully submitted to: DAYT29 }` it would be better than a basic string... I'm not sure what the point of specifying 'Accepts': 'application/json' in the header is for if they don't respect it 👎

**Comment by U-DON** [comment]
@saneshark The refill count doesn't change, at least not right away from what I see so far. Like before, the status of the prescription does change to pending, so it looks like something is happening server side.

**Comment by ayaleloehr** [comment]
Email sent to Ken asking why they are sending back a string instead of JSON. will follow up here as soon as I hear back. @saneshark is there any sort of workaround we can put in for testing in the mean time so that at least the 200 is passed back to the frontend instead of a 500?

**Comment by saneshark** [comment]
Without testing to see that the string is exactly 'Successfully submitted to: DAYT29' this and not something more, there isn't really a good way to be certain. I tried to look for a prescription to test with but that are all `is_refillable: false`

**Comment by ayaleloehr** [comment]
@saneshark if you go to https://staging.vets.gov/api/v0/prescriptions/active there are a number of prescriptions that have `is_refillable: true`.  Although that now makes me realize that prescriptions sometimes are refillable from the /active call but not from the /history call, which is totally wonky.  Adding it to my list of questions for Ken/Muazzam.

**Comment by ayaleloehr** [comment]
@U-DON this should be fixed now with the most recent deploy to staging. Give it a try when you can and let us know!

**Comment by U-DON** [comment]
@ayaleloehr Yup, getting a successful response now. :+1:
