### ISSUE TITLE
[Secure Messaging] POST request to create a new folder causes a 500 error

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-api#168]
Made a `POST` request to `/api/v0/messaging/health/folders` with the following request headers and payload (lemme know if you'd rather have this as text):

<img width="541" alt="screen shot 2016-09-26 at 7 19 53 pm" src="https://cloud.githubusercontent.com/assets/354277/18858071/440d69a6-841e-11e6-8c65-d7418ffc87a3.png">

Received the following response:

`{"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":500}]}`

**Comment by ayaleloehr** [comment]
It looks like the payload is `{folder: "sample folder"}` but should be
```
{
  "folder": {
    "name": "sample folder"
  }
}
```
Does that fix it @webinista ?

**Comment by webinista** [comment]
It does! Thanks. Tired eyes can't read very well.
