### ISSUE TITLE
Parameterize LOA policy for /sessions/new

### ISSUE THREAD

**Issue by shauni** [department-of-veterans-affairs/vets-api#173]
The authentication context for the SAML request is currently hardcoded:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/saml_settings.rb#L15

This should be a parameter in the `/sessions/new` endpoint so we can request both.

**Comment by omgitsbillryan** [comment]
@shauni I dont think we need this anymore.  Possibly something that is local dev environment only (such as a commented out route) but nothing that would go in staging or prod.  Can I close?

**Comment by robbiethegeek** [comment]
This is blocked by the conversation and decisions being made by @staceylanger

**Comment by staceylanger** [comment]
What decision needs to be made, specifically?

**Comment by shauni** [comment]
@staceylanger - whether we are defaulting to LOA3 for everybody or whether we are going to allow different LOAs.

@omgitsbillryan - at the very least we need to update the hardcoded default to be `LOA3` and not `authentication`. Ideally we would also include a dev-only URL parameter that would force the `authentication` policy, so developers can test without having to restart the server.

**Comment by staceylanger** [comment]
Thanks! I will say that we will allow more than one LOA level. Reasons:

For things like "saving an in progress form" we don't need the user to go through the trouble of LOA3 proofing.

We pay for every LOA2 and LOA3 account, so we want to ensure they are only used when needed.

**Comment by omgitsbillryan** [comment]
The endpoint on the ID.me side is the same irrespective of the LOA desired.

```https://api.idmelabs.com/saml/SingleSignOnService?SAMLRequest=fVJ2E....```

Only thing that changes is the `authn_context` value in the encoded+encrypted `SAMLRequest` url query parameter.

**Comment by robbiethegeek** [comment]
https://github.com/department-of-veterans-affairs/vets-api/tree/loa3-session-hack

@omgitsbillryan I worked on a branch to get this working for @crwallace to continue testing, this has a working solution of adding ?level=high for LOA3 and without it LOA1.  

Please take a look and see if this can be used going forward (it is already rebased against @kreek's PR that got merged in).

Needs tests :)

**Comment by omgitsbillryan** [comment]
This work has been completed.
