### ISSUE TITLE
Errors getting serialized with status field as integer, not string

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#174]
JSON API says that the status field of an error object should be a string:
```
status: the HTTP status code applicable to this problem, expressed as a string value.
```
When I generate an exception like:
```
raise Common::Exceptions::InvalidFieldValue.new('services', unknown)
```
the output has status as an integer:
```
{"errors":[{"title":"Invalid field value","detail":"\"[\"OilChange\"]\" is not a valid value for \"services\"","code":"103","status":400}]}
```

**Comment by saneshark** [comment]
Thanks for identifying this. I think we're using that status in ApplicationController to set the appropriate status as well. I'm assigning this to myself because I'm aware of that constraint, but documenting it here in case someone else ends up taking this issue item.
