### ISSUE TITLE
[526/4142 Email] Update Form526SubmissionRemediation model to support email remediation

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/vets-api#18767]
## Context
Upcomming work to email Veterans when their submission fails requires some tweaks to our failure tracking. We are going to count the sending these emails as a form of 'remediation', so it makes sense to leverage the existing Form526SubmissionRemediation model.

A few changes are required

- [x] create `remediation_type` value on model with default of `0` (this will be "manual")
- [x] refactor the model to have an enum that leverages this value providing types
  - manual
  - ignored_as_duplicate
  - email_notification
- [ ] migrate application logic 
  - update existing ignored_as_duplicate: true values to new paradigm
  - update Form526Submission state scopes to use new paradigm
- [ ] remove ignored_as_duplicate value

## Resources

- [Scopes Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_scopes.md)

**Comment by lisacapaccioli** [comment]
@SamStuckey Can you add a description to this ticket. Something that tells us what it means and why it's necessary (benefit). I need to add it to our work for ZSF for tracking. Thanks
