### ISSUE TITLE
Address backend errors in facilities locator

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#188]
Address generic and application-specific errors coming from backend GIS service(s). 
- Connection errors and timeouts.
- Application errors. Looks like maps.va.gov (interim backend) typically returns a 200 status but a response body bearing an error message for e.g. cases where a query cannot be completed:

```
{
 "error": {
  "code": 400,
  "message": "Failed to execute query.",
  "details": [  
  ]
 }
}
```

**Comment by jcmeloni** [comment]
@patrickvinograd Still doing something here or have these been taken care of? (we're trying to clean up issues)

**Comment by patrickvinograd** [comment]
This is done. Closing.
