### ISSUE TITLE
Add pagination to Facilities Locator API

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#189]
Currently no limits on facilities locator query - it will return all results in the supplied bounding box. Follow API style guide to add pagination parameters, though consider tuning default number of results for good user experience in the map pane. 

This will require frontend effort to allow paging forward/backward through available facilities.

**Comment by saneshark** [comment]
If you're able to Marshall a complete list of facilities into Common::Collection a lot of the heavy lifting for pagination, filtering, and sorting will be done for you. Examples include `PrescriptionsController` and `MessagesController` `index` actions.

**Comment by patrickvinograd** [comment]
In progress with #437

**Comment by patrickvinograd** [comment]
Closed via #437.
