### ISSUE TITLE
Uses cases for sending/saving/deleting messages, replies, and drafts

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-api#194]
I have attempted to enumerate all the cases we need to cover when it comes to working with messages, replies, and drafts. I also have the requests and payloads in certain cases as I think they're supposed to be used. Feel free to correct me if their usages are incorrect.

My main points of confusion are mostly with replies.
- For step [2.2], I'm not sure if it's the same as [1.2], and if so, how does it get associated with the message/thread that the user is replying to? Creating a draft also requires category, subject, and recipient id, but a reply should only require body.

> Saving a draft that is intended as a reply is precisely the same as saving a draft that is intended as a new message. Ideally, the vets-api would implement a replydraft endpoint for you to call with the body that would do the association for you. However, we are not currently implementing that endpoint nor are we using the MHV replydraft endpoint. Ideally when you get the draft using the GET /v0/messaging/health/messages/:id route, you simply pass the body of the draft and the drafts id in the payload. However, since the replydraft route is not implemented, you would (1) have to retrieve the draft, and (2) have to create and send a new reply using the information from the draft you've just retrieved.
- Similarly, I need to know how to update the draft of a reply in [2.2.2].

> Updating a draft that is intended as a reply is precisely the same as updating a draft that is intended as a new message.
- For [2.2.1], I realize I need to send a regular reply with the contents of the draft and then delete the draft in a separate request, but I'm not sure where to get the id of the message the user is replying to. It comes back to knowing how to associate the draft with the message it's replying to.

> Unfortunately, no matter how we were to implement replies with drafts (either hacking it as we are doing now, or using the MHV/Vets-api endpoint replydraft) you would still need to provide both the draft id and the reply id. The :id of the message to which you are replying is part of the url: 
> POST    /v0/messaging/health/messages/:id/reply
> and the draft's id you are replying with in the payload.
## User flow
- Write new message
  - [1.1] Send message
    
    ```
    POST /messaging/health/messages
    
    {
        "message": {
            "category": "Category from list",
            "subject": "Message subject",
            "body": "The message body",
            "recipient_id": 1
        }
    }
    ```
  - [1.2] Save draft of message
    
    ```
    POST /messaging/health/message_drafts
    
    {
        "message_draft": {
            "category": "Category from list",
            "subject": "Message subject",
            "body": "The message body",
            "recipient_id": 1
        }
    }
    ```
    - Edit draft
      - [1.2.1] Send draft
        
        ```
        POST /messaging/health/message
        
        {
            "message": {
                "id": 5
                "category": "Category from list",
                "subject": "Message subject",
                "body": "The message body",
                "recipient_id": 1
            }
        }
        
        // Until draft is deleted automatically by passing id in payload,
        // make a separate delete request:
        DELETE /messaging/health/message/:id
        ```
      - [1.2.2] Update draft
        
        ```
        PUT /messaging/health/message_drafts/:id
        
        {
            "message_draft": {
                "category": "Category from list",
                "subject": "Message subject",
                "body": "The message body",
                "recipient_id": 1
            }
        }
        ```
      - [1.2.3] Delete draft
        
        ```
        DELETE /messaging/health/messages/:id
        ```
  - [1.3] Delete message (no API call, just clear the inputs)
- Write reply to message
  - [2.1] Send reply
    
    ```
    POST /messaging/health/messages/:id/reply
    
    {
        "message": {
            "body": "The message body",
        }
    }
    ```
  - [2.2] Save draft of reply (?)
    - Edit draft
      - [2.2.1] Send draft (?)
        
        ```
        POST /messaging/health/message/:id/reply
        
        {
            "message": {
                "body": "The message body",
            }
        }
        
        // This is the id of the draft.
        DELETE /messaging/health/message/:id
        ```
      - [2.2.2] Update draft (?)
      - [2.2.3] Delete draft
        
        ```
        DELETE /messaging/health/messages/:id
        ```
  - [2.3] Delete reply (no API call, just clear the inputs)

**Comment by ayaleloehr** [comment]
Marc to respond today.

**Comment by saneshark** [comment]
@mphprogrammer for message#create when a draft is sent, can we make sure the #create action on messages controller can receive the draft_message_id and merge that in to the params we send MHV so it is automatically deleting drafts when provided?

Lets please call it something descriptive though. I'm not entirely sure how it would conform to JSONAPI because it's not really an attribute of the object being created. I'm leaning towards us requiring it as a separate parameter, not part of the `{ data: { type: 'message', attributes: { ... } }}`

**Comment by mphprogrammer** [comment]
@saneshark Currently, because of my PIV problems I cannot actually use my VA laptop - and hence, have no network access. As of now, all I would need to do is add :id to message_params.

**Comment by mphprogrammer** [comment]
@U-DON I've answered (tried to, anyway) your questions in your original comment. MHV is very limited in draft support - you can only create, delete, and update a draft, and pass its :id in the payload section of a message create or reply call.

**Comment by U-DON** [comment]
@mphprogrammer The parts about the drafts endpoints and their usages (same for replies as for new messages) make sense to me. What's still blocking my entire understanding of how to convert a draft to a reply is where I get the reply id.

If I retrieve a draft with `GET /v0/messaging/health/messages/:id`, where `:id` is the draft id, I can't simply append `/thread` to get the thread it's intended to be a part of, since it was saved in the same manner as saving a draft for an entirely new message. So I have no way of knowing what message it's replying to and what id to provide for the reply endpoint. Am I missing something?

If it helps, here's the mental model I have of specifically accessing a draft to send as a reply:

First, I go to the drafts folder. Then I get a list of its messages. Then I go to one of those messages (retrieved via the GET mentioned above). I would like to send it as a reply, but then I don't know what id to use for the reply endpoint.

**Comment by mphprogrammer** [comment]
@U-DON That is the weakness of the MHV scheme. You need to know the reply endpoint when you are replying with a draft. The draft object has no knowledge of what its being used for (ie, MHV doesn't allow a :reply_id in the payload of the draft). I wish I had a better answer, but right now that is how it is implemented by MHV. I suppose you would have to have the user select the message being replied to and then provide an option to enter a reply in the form or select from existing drafts.

**Comment by mphprogrammer** [comment]
@ayaleloehr I was under the impression that we had decided not to do reply-with-draft because of the MHV wonkiness.

**Comment by saneshark** [comment]
Is this ticket resolved?

**Comment by U-DON** [comment]
Yeah, I think I have an understanding of all the cases now and how they need to be handled in terms of API requests.
