### ISSUE TITLE
Admin panel: what's needed?

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-api#203]

**Comment by jcmeloni** [comment]
@akainic Is this part of the Veterans Day requirements? Thanks!

**Comment by akainic** [comment]
@jcmeloni I don't think so, post Veterans Day!

**Comment by robbiethegeek** [comment]
What is this an admin panel for?

**Comment by akainic** [comment]
For education benefits. Would allow education services members to do things like send an application to a different RPO or check on the status of an application (I think, @markolson can correct me if wrong).

**Comment by markolson** [comment]
Yep, for forms we need a way to handle situations where the form may need to be pulled down again, or viewed by someone in a call center or processing office.

**Comment by leannammiller** [comment]
hey @markolson - has there been any movement on this? do we have a sense of the priority of this?

**Comment by markolson** [comment]
No movement on this, and since we've been live for a while and have had no requests for it's functionality, I'd say it can remain low priority.

**Comment by ayaleloehr** [comment]
@J-Quag if this is something on the roadmap, can you move it to vets.gov-team? (or just close?)

**Comment by J-Quag** [comment]
Opening new ticket in Vets.gov-Team. Closing this.
