### ISSUE TITLE
Support LOA1 / LOA3 on resource paths

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#243]

**Comment by omgitsbillryan** [comment]
I'll provide more details:

**Description**
We need an authorization framework in place the protect various resources on vets-api.  The levels are:

1. No AuthZ required (e.g. `/sessions/new`)
2. LOA1 required (e.g. `/profile`)
3. LOA3 required (e.g. `TBD`)

**Use Case**
As a user who has authenticated with ID.me at LOA1, I request an LOA3 resource, I should receive `403 forbidden` and a json body that describes why.

**Discovery Needed**
- Do we use a library (like [CanCan](https://github.com/ryanb/cancan) or roll our own solution?

**Comment by jcmeloni** [comment]
@omgitsbillryan @robbiethegeek Here's info collected from the various shared data / needs lists. LMK what else you need.


<table>
<tr>
   <th>Name</th>
  <th>AuthZ</th>
  <th>Data Needed from MVI</th>
</tr>
<tr>
   <td>Facility Locator</td>
  <td>none</td>
  <td>none</td>
</tr>
<tr>
   <td>Health Care Application</td>
  <td>none</td>
  <td>none</td>
</tr>
<tr>
   <td>Benefits Explorer</td>
  <td>none</td>
  <td>none</td>
</tr>
<tr>
   <td>Education Benefits</td>
  <td>none</td>
  <td>none</td>
</tr>
<tr>
   <td>Benefits Explorer</td>
  <td>none</td>
  <td>none</td>
</tr>
<tr>
   <td>User Profile</td>
  <td>LOA1</td>
  <td>none</td>
</tr>
<tr>
   <td>Prescription Refill</td>
  <td>LOA3</td>
  <td>mhv_id</td>
</tr>
<tr>
   <td>Secure Messaging</td>
  <td>LOA3</td>
  <td>mhv_id</td>
</tr>
<tr>
   <td>Disability Claim Status</td>
  <td>LOA3</td>
  <td>edipi<br/>vba_corp_id<br/>ssn</td>
</tr>
</table>

**Comment by jcmeloni** [comment]
@omgitsbillryan @robbiethegeek The aforementioned table ^^

**Comment by robbiethegeek** [comment]
@aub we can close this as complete now SM went in today

**Comment by aub** [comment]
Slammin
