### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#245]
Caching + cache busting

**Comment by ayaleloehr** [comment]
Separate out session vs get request.

**Comment by saneshark** [comment]
[ ] - Session Caching (see #254)
[ ] - Caching and Cache Busting of Get Requests (this is not currently possible design document for caching - currently pull request in platform-api)

**Comment by ayaleloehr** [comment]
Open PR @saneshark wrote for cache busting (checkbox two above): https://github.com/department-of-veterans-affairs/platform-team/pull/148

**Comment by ayaleloehr** [comment]
Closing as too broad. Will open separate issues.
