### ISSUE TITLE
Add a re-route mechanism for applications

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-api#249]
Sometimes applications are sent to the "wrong" processing center, usually because of some user input error or mistake, and the application needs to be re-sent to a different processing center.

**Comment by jcmeloni** [comment]
@akainic @markolson If this is something we need to have in for Veterans Day, could you please throw the veterans-day tag on it? Thanks!

**Comment by akainic** [comment]
@jcmeloni I don't think it's something we absolutely need to have by Veterans Day, but @markolson can correct me if I'm wrong on that

**Comment by markolson** [comment]
I don't think it's part of an MVP for launch, but I want to get cracking on it sooner rather than later.

**Comment by jcmeloni** [comment]
Cool. We won't label it veterans-day but let's all keep on truckin'! :)

**Comment by akainic** [comment]
Code is there, needs better documentation. Also need to change the filename of the spool file so that we can do multiple submissions per day.

**Comment by akainic** [comment]
Work happening week of 11/21, but not deploying to production that week.

**Comment by akainic** [comment]
Work has been deployed, will learn more once an actual re-direct is requested us of. Will close for now.
