### ISSUE TITLE
Create Education Form Submission Model & Controller

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-api#25]

**Comment by lihanli** [comment]
redis_store currently deletes records if it finds them and sees they arent valid, do we want this for our records?

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/redis_store.rb#L17-L27

**Comment by lihanli** [comment]
another problem is we will want to look up all claims submitted within a time range and that's tricky with redis, i think we should use postgres instead

**Comment by markolson** [comment]
We want this to be a database-backed model, yes.
