### ISSUE TITLE
Sorting prescriptions when dates can be null

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#253]
Sorting prescriptions seems to not work when the field you're sorting on is sometimes null. One example currently is https://staging-api.vets.gov/v0/prescriptions?sort=dispensed_date doesn't seem to actually sort by dispensed_date.

cc both @saneshark and @mphprogrammer as I'm not sure which of you will have time to work on this first

**Comment by saneshark** [comment]
This issue is a duplicate of #127

**Comment by ayaleloehr** [comment]
I knew it was somewhere!  Well, I'll close that one and leave this one open.  For our records, this is originally from https://github.com/department-of-veterans-affairs/prescriptions-api/issues/67

**Comment by jcmeloni** [comment]
@ayaleloehr If this is something we want to fix up for Veterans Day, could you please throw the veterans-day tag on it? Thanks!
