### ISSUE TITLE
PDF Fill - Form value string data is always formatted as date

### ISSUE THREAD

**Issue by dmccurdybah** [department-of-veterans-affairs/vets-api#2725]
PDF form string data containing date information is formatted as a date which can result in lost data.

Form data is converted in `hash_converter.rb`, and the `convert_val_as_string` method attempts to split every string on `-` and only checks if the result is a valid date.

This means that a value like "Treatment was between 1995-1-1 and 1996-1-15" will be converted to "01/01/0000".

**Comment by dogweather** [comment]
Resolved by #2722
