### ISSUE TITLE
Add rails_12factor gem to enable logging to standard out

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#273]
This is a devops/app standardization requirement.

**Comment by robbiethegeek** [comment]
@patrickvinograd can you please add more details / help me understand the priority  and LOE for this...

**Comment by patrickvinograd** [comment]
12 factor gem is described here: https://github.com/heroku/rails_12factor

Since vets-api does not serve any assets the only functional change is logs going to standard out instead of production.log. We are already redirecting standard out to a file and capturing both that and production.log to cloudwatch, but in the future this will give us flexibility to use some other log aggregation tool and stream logs directly from standard out. 

Mainly it's just a consistency thing - we've done this across the board for all devops-deployed apps except vets-api.

**Comment by patrickvinograd** [comment]
LOE is just adding rails_12factor to Gemfile.

**Comment by jcmeloni** [comment]
@patrickvinograd Has this been done/does it still need to be done? (we're trying to clean up issues)

**Comment by patrickvinograd** [comment]
Not done yet. Still desirable. I can knock it out today, but let me confirm with other devops people that there's no downstream impact, there is some log processing work going on.
