### ISSUE TITLE
update authentication documentation

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/vets-api#2746]
The documentation in https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/authentication_with_idme.md
refers to token authentication and we need to update it to refer to cookies.

**Comment by saneshark** [comment]
I think @kreek has done some of work with simplifying cookie based testing using a rake task, perhaps the instructions could include details related to that.

**Comment by BBarone1** [comment]
moved this to a planning issue here  #17961

closing
