### ISSUE TITLE
Separate JSON /profile Schemas for LOA 1 & 2

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/vets-api#284]
Right now we only have one JSON schema for `profile`.  However, the attributes for LOA1 vs LOA3 are different enough to warrant a schema for each.  This issue is to refactor the profile.json schema into two separate schemas for LOA 1 & 3.

**Comment by jcmeloni** [comment]
@omgitsbillryan Is there any more action we need to do on this or can it be closed since the PR is merged? cc @robbiethegeek

**Comment by omgitsbillryan** [comment]
This has not been completed - must remain open.

**Comment by robbiethegeek** [comment]
@omgitsbillryan this can be closed now right if not can you please add more steps / details of the remaining steps.

**Comment by omgitsbillryan** [comment]
@robbiethegeek this issue came _as a result_ or the merged PR and cannot be closed.  I think the OP still applies and no new steps are needed.

**Comment by jcmeloni** [comment]
@omgitsbillryan @robbiethegeek How can we get this closed up? Anyone have suggestions for Bill's PR re: being DRYer?

**Comment by omgitsbillryan** [comment]
PR has been merged.
