### ISSUE TITLE
Cleanup Session Cookie feature toggle code

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/vets-api#2889]
When we launched session cookies, we did it with feature toggling. Now that its implemented, there is no plan to revert back and the code is too far along to even consider doing it at this point, so its time to do a little cleanup.

Removes the feature toggle stuff from vets-api
https://github.com/department-of-veterans-affairs/vets-api/pull/2884

Remove the feature toggle flag from the ansible settings.yml overrides.
ansible/deployment/config/vets-api/*-settings.local.yml.j2 etc...

**Comment by saneshark** [comment]
Closing out 2885 is not enough to close this ticket. Need to also update the devops ansible configs.

**Comment by BBarone1** [comment]
@annaswims updated ansible configs, this work is done
