### ISSUE TITLE
Messaging: Getting 400 Bad Request errors

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-api#292]
When trying to send a message -- with or without attachments -- I'm getting errors from the API. Example request:

<img width="848" alt="400error" src="https://cloud.githubusercontent.com/assets/354277/19461007/ac034f6c-9495-11e6-9926-372997e0c0ac.png">

What am I doing wrong?

**Comment by saneshark** [comment]
It would appear as though your request has content-type of `multipart/form-data` - I would send these messages as a normal `application/json` message body unless you actually have `uploads[]` - I could look at providing a more detailed error message though. What kind of error are you getting?

**Comment by webinista** [comment]
I posted this in Slack, but I think it's probably easier to track down here.

Here's an example request as copied-and-pasted from Chrome's dev tools.

```
curl 'http://localhost:3001/api/v0/messaging/health/messages' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3001' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,fr;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' -H 'content-type: application/json' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3001/messaging/compose' -H 'Connection: keep-alive' -H 'x-key-inflection: camel' -H 'DNT: 1' --data-binary '{"message":{"category":"APPOINTMENTS","subject":"","body":"This is a message.","recipientId":585968}}' --compressed
``` 

The error message I'm getting is a 500 status message containing the following, very unhelpful JSON: `{"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":"500"}]}`

I can provide a request ID and date if it helps. This _may_ be an issue of timing out. There's an `x-runtime` response header with a value of `15.294694`

**Comment by saneshark** [comment]
@webinista I tested the curl script above against my local server while on the VA network connecting to the same syst server that staging uses. The internal server error appears to be the result of MHV request timing out -- I'm going to play around with it a bit, to see if I can get more information before going back to MHV to explain this issue.

**Comment by saneshark** [comment]
Ok, so I increased the read_timeout setting from 15 seconds to 60 seconds, and I counted. After about 39 seconds the request completed and returned the expected response for a newly created message. So this would suggest that it is entirely an issue on MHV's side and that for whatever reason, the 10 second SLA that they promise is not being met after the recent changes they made.

Tagging @ayaleloehr on this as well.

**Comment by webinista** [comment]
Here's an example of a cURL request (from Chrome's DevTools) that's similar to the one that triggered a `400 Bad Request` response (before we discovered that there's also an MHV problem). 

```
curl 'http://localhost:3001/api/v0/messaging/health/messages' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3001' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,fr;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryH8oqMpi8SLL7JOAP' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3001/messaging/compose' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary $'------WebKitFormBoundaryH8oqMpi8SLL7JOAP\r\nContent-Disposition: form-data; name="message"\r\n\r\n{"category":"APPOINTMENTS","subject":"","body":"Another test request.","recipientId":585968}\r\n------WebKitFormBoundaryH8oqMpi8SLL7JOAP--\r\n' --compressed
```

Here's what Chrome reports as the Request headers:

```
    POST /api/v0/messaging/health/messages HTTP/1.1
    Host: localhost:3001
    Connection: keep-alive
    Content-Length: 230
    Pragma: no-cache
    Cache-Control: no-cache
    Origin: http://localhost:3001
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like    Gecko) Chrome/53.0.2785.143 Safari/537.36
    content-type: multipart/form-data; boundary=----WebKitFormBoundaryH8oqMpi8SLL7JOAP
    Accept: */*
    DNT: 1
    Referer: http://localhost:3001/messaging/compose
    Accept-Encoding: gzip, deflate
    Accept-Language: en-US,en;q=0.8,fr;q=0.6
```

Here's what Chrome reports as the payload:

```
------WebKitFormBoundaryH8oqMpi8SLL7JOAP
Content-Disposition: form-data; name="message"

{"category":"APPOINTMENTS","subject":"","body":"Another test request.","recipientId":585968}
------WebKitFormBoundaryH8oqMpi8SLL7JOAP--
```

## Important details

- The payload was assembled using the `FormData` API
- The request is a [fetch](https://fetch.spec.whatwg.org/) request (successor to XMLHttpRequest) 

Both are browser-native APIs. 

- Using `FormData` automatically sets the `content-type: multipart/form-data; boundary=----WebKitFormBoundaryH8oqMpi8SLL7JOAP` header
- Using `FormData` automatically sets a `Content-Disposition: form-data;` header for each item sent.
- Modifying the `Content-Disposition` header  **is not possible.**
- We can send correctly-formatted JSON for `message`. It just won't have an `Content-Disposition: application/json;` header. 

### Outstanding question(s)

- What the `Content-Disposition:` headers for attachments look like.
- How best to add attachments file data (see the discussion in department-of-veterans-affairs/messaging-fe#100)

**Comment by saneshark** [comment]
@webinista so MHV might have resolved the issues on their side, I'm not getting the same timeout issues. The problem you're describing is definitely with how the data is being sent though.

When your content disposition is form-data, name: "message" and the data is json, Rails has no way of marshalling that into individual parameters. It's going to treat it as message = "your json string" vs message = { "keys": "and values within" }

**Comment by saneshark** [comment]
Since you cannot change the content disposition, instead you will need to provide form data for each and every component as its own separate form data part in the multipart request.
where name:

message[category]
message[subject]
...

**Comment by saneshark** [comment]
Your first curl request you provided though works perfectly. It's this second one that will cause issues.

**Comment by saneshark** [comment]
I will leave this issue for now and let you close this, but this does not appear to be a bug, it's definitely a bad request 400 from what I'm seeing.

**Comment by webinista** [comment]
Is it possible to accept `message` and then parse the JSON string that we send into a Rails-friendly object?

**Comment by saneshark** [comment]
yes, but the content disposition must match the data type or rails doesnt know if its a string as part of form-data or application/json, or whatever. The content disposition is the mimetype for the part of the multipart basically, without it rails can only treat it as a raw string, not as json.

**Comment by webinista** [comment]
Using snake cased keys was the trick.
