### ISSUE TITLE
Figure out UI for User Profile data being incorrect...

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#300]
This is going to involve letting the user know where the data lives and how to update it. 

If it is ID.me likely they will have to run over there to update, created a ticket for tracking updating the data in MVI #299

**Comment by axle07** [comment]
@robbiethegeek can you provide a little more detail? I'd love to contribute.

**Comment by robbiethegeek** [comment]
Thanks for reaching out, please review the README.md for info about the contribution policy: 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/README.md

**Comment by axle07** [comment]
Cool. Is there any more specification regarding this UI (how it should
look, where it should live)?

**Comment by jcmeloni** [comment]
Closing issue - we have a discovery ticket in team repo.
