### ISSUE TITLE
Sessions endpoint LOA level validation (revisit)

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#311]
Revisit the validation of the level being passed in:

We could still raise an error here if there is a bad level provided if that is the desired functionality. Also, you can remove the nil check, nil.to_i = 0

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/application_controller.rb#L71

**Comment by jcmeloni** [comment]
@robbiethegeek We're through fiddling with this, right? Can close?

**Comment by robbiethegeek** [comment]
I assigned to @omgitsbillryan to review and close

**Comment by omgitsbillryan** [comment]
I will take a look today.

**Comment by omgitsbillryan** [comment]
I think it's OK to default to `level=1` in the event that an invalid level is supplied.  PR: https://github.com/department-of-veterans-affairs/vets-api/pull/583

`level` is whitelisted to 1 or 3 FWIW.
