### ISSUE TITLE
Correcting the Appeals Status API documentation

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/vets-api#3110]
After reading through the documentation for the Appeals Status API

https://developer.va.gov/explore/benefits/docs/appeals

( vets-api/modules/appeals_api/README.yml )

it looks like it needs to be updated to fix a mistake in the description of the return data for the appeals status endpoint.

The description of that endpoint in appeals_api/README.yml indicates that the data attribute would always be an object. This was confusing to me --it seemed like it should be an array, with each element of the array being an active decision review request that was in the pipeline, since vets can appeal more than 1 decision at a time. After discussing this with Peter Karman of the caseflow team ( https://dsva.slack.com/archives/C2ZAMLK88/p1560396287096000 ), it appears that this endpoint might actually return an array instead of an object (if there are multiple appeals for a single vet). During this discussion we agreed that the data attribute's value should always be an array, in keeping with the JSON:API spec, and Peter made a ticket for this (ensuring that data is always an array) in the caseflow repo ( https://github.com/department-of-veterans-affairs/caseflow/issues/11084 ).

Additionally, README.yml does not describe the docs endpoint ( services/appeals/docs/v0/api ) nor, more importantly, the API healthcheck status endpoint ( services/appeals/v0/healthcheck ).

Peter Karman's notes on this API (in the caseflow repo) ( https://github.com/department-of-veterans-affairs/caseflow/blob/pek-api-docs/docs/caseflow-apis.md#vagov-appeals-status ) has a lot of useful information. I see that it's also using "v2" in the paths, which probably also needs to be looked into.

Lastly, team Banana Peels has some scheduled discussion on Monday (2019-06-17) about the Appeals API, and taking ownership of the appeals status stuff could be discussed (in addition to whether or not having vets-api as a wrapper is necessary

**Comment by bastosmichael** [comment]
This should probably exist in vets-contrib instead of here.

**Comment by edmangimelli** [comment]
moving this to vets-contrib (zenhub)
