### ISSUE TITLE
Sender and recipient are swapped for messages in a collection?

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-api#315]
When I go to any folder, the sender and recipient values seem to be swapped. For example, the most recent message (id 634998) in Inbox (`/messaging/health/folders/0/messages`) has MVIONE, TEST as the sender, but I believe that's the test user. And the recipient is KARSHENAS, KAMYAR instead. When I go to the message itself (`/messaging/health/messages/634998`), it's the other way around.

**Comment by mphprogrammer** [comment]
It really shouldn't be, that's odd. Both endpoints collection and non-collection use Message. Let me look into this.

**Comment by mphprogrammer** [comment]
Well, I'm dead in the water now ... 
<HTML>
    <HEAD>
        <TITLE>Weblogic Bridge Message
</TITLE>
    </HEAD>
    <BODY>
        <H2>Failure of server APACHE bridge:</H2>
        <P>
            <hr>No backend server available for connection: timed out after 10 seconds or idempotent set to OFF.

            <hr>
            <BR>
            <B>Build date/time:</B>
            <I>Apr 20 2009 15:29:34</I>
            <P>
                <HR>
                <B>Change Number:</B>
                <I>1211636</I>
            </BODY>
        </HTML>

**Comment by mphprogrammer** [comment]
@U-DON OK - MHV is down right now, but I looked at some old vcr recordings. It looks like that's the way it comes back from MHV!! 

When we call MHV to return all messages in a folder, we get the json
```
'{"message":[{"id":573302,"category":"OTHER","subject":"Release 16.2-
        SM last login ","body":null,"attachment":false,"attachments":null,"sentDate":"Wed,
        13 Apr 2016 21:17:57 GMT","senderId":384939,"senderName":"MVIONE, TEST","recipientId":35382,"recipientName":"Manivasagam,
        Rajesh","readReceipt":"READ"},{"id":573052,"category":"OTHER","subject":"Release
        16.2- SM last login ","body":null,"attachment":false,"attachments":null,"sentDate":"Mon,
        11 Apr 2016 15:49:03 GMT","senderId":384939,"senderName":"MVITWO, TEST","recipientId":257555,"recipientName":"ISLAM,
        MOHAMMAD","readReceipt":"READ"}]}'
```
Take a look at the last message`573052`.  When we retrieve that message, MHV sends back the following json:
```
{"id":573302,"category":"OTHER","subject":"Release 16.2- SM last login
        ","body":"fdgfdgsdfgd","attachment":false,"attachments":{"attachment":[]},"sentDate":"Wed,
        13 Apr 2016 21:17:57 GMT","senderId":35382,"senderName":"Manivasagam, Rajesh","recipientId":384939,"recipientName":"MVIONE,
        TEST","readReceipt":"READ"}'
```

The recipient and sender is switched! Great Catch!! I will let the folks at MHV know tomorrow.

**Comment by saneshark** [comment]
I believe I sent this as MVIONE TEST from the admin interface. sorry for the confusion.

**Comment by ayaleloehr** [comment]
@U-DON can you see if this happens again? MHV says they fixed this today.

**Comment by U-DON** [comment]
Yup, works correctly now!
