### ISSUE TITLE
Rx caching GET requests

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#341]
- To be implemented in Redis per [this](https://github.com/department-of-veterans-affairs/devops/issues/828#issuecomment-255201506) thread (great conversation there!). 
- Cache GET requests, then make sure future requests use this cached result (if it exists) rather than calling MHV. 
- Should bust cache for all of that user's Rx GET requests when a POST is performed.
- Should have an expiration on the cache as well. Must be less than 1 hour per our ISA/MOU.

**Comment by saneshark** [comment]
@ayaleloehr is it ok to remove the veterans-day label from this since its no longer required before 11/11 milestone?

**Comment by ayaleloehr** [comment]
After conversations with MHV team, this will be a nice to have and I still think we should do it, but it not being there isn't blocking launch, so removing `veterans-day` label

**Comment by saneshark** [comment]
See also #342 -- would like to prioritize this before MHV June release or whenever the email notifications for Rx are supposed to start going out.

**Comment by leannammiller** [comment]
@saneshark can you please estimate this?

**Comment by saneshark** [comment]
@ayaleloehr I went ahead and did the work on this, I've currently got Rx cached at 10 hours in my PR, why exactly does it need to be 1 hour? The reason I ask is, Rx data is only refreshed by MHV every 24 hours, we could easily get away with a longer lived cache, but I guess it would require further IAM approval?

**Comment by ayaleloehr** [comment]
A brief look at our Privacy Impact Assessment (PIA) shows that we don't have caching prescription data in there currently.  (see section 3.2, on pages 27 and 28 of [PIA_vets.gov 20170620_signed.pdf](https://github.com/department-of-veterans-affairs/vets-api/files/1190644/PIA_vets.gov.20170620_signed.pdf))

I believe that to start caching this data, we will need to update the section under "for 24 hours" to include "Prescription refill" and "secure messaging".  @saneshark should it also include "Blue Button"?  And @brianheckethorn does that seem accurate, and if so, can you please create an issue in vets.gov-ato and track that through to Rita for approval (hopefully with an interim approval, but I'm not sure how that works).

**Comment by leannammiller** [comment]
@saneshark what is the status of this?

**Comment by saman7352** [comment]
#342

**Comment by NatalieEMoore** [comment]
any update on this @saneshark

**Comment by leannammiller** [comment]
@brianheckethorn please follow up here

**Comment by jkassemi** [comment]
@leannammiller do you know if Brian followed up here?

**Comment by leannammiller** [comment]
He sure didn't @jkassemi. I will add this to the list of things that need to be updated in our PIA/PTA.

**Comment by raquelromano-gov** [comment]
Moving this to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6699 and closing here.
