### ISSUE TITLE
SM caching GET requests

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#342]
Similar to #341 but potentially more complex because (1) there are far more POSTs in SM and (2) Veterans will receive messages back at a more frequent rate than their prescription info will change.  With that, the cache here should likely be pretty short, on the order of minute(s).  Other context from #341 still is relevant though.

**Comment by leannammiller** [comment]
@saneshark please estimate

**Comment by saneshark** [comment]
estimated at 5 hours of coding, but we will probably maybe want to do regressions too.

The PR for Prescriptions is much easier / safer than this one. If that one can get launched first, then I'll have more confidence in the approach and this one will be easier.

**Comment by saman7352** [comment]
#342

**Comment by leannammiller** [comment]
Hi @saman7352 - this a new username for me. Are you on the Vets.gov team?

**Comment by raquelromano-gov** [comment]
Replaced by https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6699
