### ISSUE TITLE
Account activity login for MHV

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#343]
When a user uses the Rx or SM API's for the first time each vets.gov login session, we need to send an Account Activity Login API call to MHV.  

The current plan is to add a boolean (named something to the effect of `mhv_login_sent`) to the user profile and check that boolean every time we get an MHV session token. If the boolean says we have already sent this login call, don't send it again; if we haven't sent, send it and flip the boolean so we don't send it again.   

We need to figure out exactly what format to add this to the user profile in, so before implementing please talk to @robbiethegeek with what we plan to call the boolean and where we will put it, so that he has visibility/agrees.

**Comment by robbiethegeek** [comment]
Has this been completed? @ayaleloehr

**Comment by ayaleloehr** [comment]
No. It is high on @saneshark's priority list, but he's trying to work through an issue with Eugene right now on double messages sometimes being sent; it's a bug in the MHV API that we're just going to have to work around and is taking a bit more time than we hoped.  I'm hoping @saneshark will be able to have a PR up for this today though. Let me know if that timing causes problems.
