### ISSUE TITLE
Account Activity logout for MHV

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#344]
Similar to #343 but for logout. When user explicitly clicks the logout button, we're supposed to send a Account Activity Logout API call to MHV.  When a vets.gov session times out, however, we don't have to send any API call to MHV. 

To implement I believe the steps are: 
- We will need to call the `destroy` action on the session when a user clicks the logout button (currently we're not making an API call to do this). 
- Before removing the session from Redis, check the user object to see if the boolean is set to true saying that an MHV login call had occurred in this session. If that is the case, then we should call the MHV Logout API.  
- This call (and #343) are great use cases for the task queue, as they can happen asynchronously and the user doesn't need to know the result.

**Comment by ayaleloehr** [comment]
I believe this can be closed. @aub or @saneshark can you confirm?

**Comment by aub** [comment]
Yep, I'm closing
