### ISSUE TITLE
Error message text

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#346]
Vague card that will probably need to be broken down further before implementation, but wanted to get something down so it isn't lost.  

We will need to translate from MHV what we want errors to our users to say.  For example, if MHV gives use "User is not eligible because they have not accepted terms and conditions or opted-in", we might instead want to return "You have not yet accepted the MHV terms and conditions. Please go to MHV and log into your account to do so" (or something like that; that's a concept, not the actual words...). 

Work is being done [here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md) to define this content, so shouldn't implement until that is better locked in, but at least wanted it on our radar.

**Comment by saneshark** [comment]
This is going to require some refactoring of common exceptions I presume. I noticed you put the veterans-day label on this, but I'm worried about making this type of change so close to 11/11. Is this going to be imperative that we get it in before 11/11?

**Comment by ayaleloehr** [comment]
Not imperative we get this in before Veterans day, so removing label. But higher priority than caching, so going to move it above that in the list.

**Comment by saneshark** [comment]
I'm currently working on this issue as part of this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/585

**Comment by saneshark** [comment]
@ayaleloehr What's the priority on this? Do we have updated language we would prefer to use for when this error is encountered?

My PR to change the language for this type of MHV error has been merged, should be able to customize the message to our hearts content. Feel free to close this comment or re-assign to me with a prioritization when you get a chance.

**Comment by ayaleloehr** [comment]
This is too vague of an issue and i don't have specific things that need action here, so going to close. If there are going to be specific errors we need to change messages for, we should open separate issues.
