### ISSUE TITLE
finish daily report email

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-api#373]
- add daily report job to scheduler
- get list of people who should be emailed
- don't use STAGING_EMAIL env var and switch to GOV_DELIVERY_SERVER var

**Comment by J-Quag** [comment]
To:
Marino, Christopher M., PITC <Christopher.Marino2@va.gov>; 
VAVBAWAS/CO/224A <224A.VBACO@va.gov>; 
Alexander, Rodney, VBAVACO <rodney.alexander@va.gov>; 
BRITT, URSULA R. <URSULA.BRITT@va.gov>; 
McCollam, Carolyn, VBAVACO <Carolyn.McCollam@va.gov>; 
Norton, Shay, VBAVACO <shay.norton@va.gov>; 
DiTucci, Christina, VBAVACO <Christina.DiTucci@va.gov>

Cc: 
Orifici, Robert <robert.orifici@va.gov>; 
Haskins, Erin, VBABUFF <Erin.Haskins@va.gov>; 
Kinzie-Calloway, Shante, VBAVACO <Shante.Kinzie@va.gov>; 
Terrell, Brandye, VBAVACO <Brandye.Terrell@va.gov>; 
Mendola, Michele, VBABUFF <michele.mendola@va.gov>; 
Carraway, Schnell, VBAVACO <Schnell.Carraway@va.gov>;
Johnson, Danita, VBAVACO <Danita.Johnson@va.gov>; 
Lopez, Jude T., VBAVACO <jude.lopez1@va.gov>; 
Wayland, Steven, VBAVACO <Steven.Wayland@va.gov>



@akainic / @lihanli

**Comment by akainic** [comment]
@lihanli sorry to be just thinking of this now, but do you mind also adding my email to the list? Anne.Kainic@va.gov. Thanks!

**Comment by J-Quag** [comment]
@lihanli    @akainic 
don't hate me :)

Marino, Christopher M., PITC; 
VAVBAWAS/CO/224B;
Alexander, Rodney, VBAVACO;
McCollam, Carolyn, VBAVACO; 
Norton, Shay, VBAVACO; 
DiTucci, Christina, VBAVACO;
Terrell, Brandye, VBAVACO; 
Mendola, Michele, VBABUFF;
Lopez, Jude T., VBAVACO;
Sutherland, Christopher, VBAVACO;
McNeal, John, VBAVACO;
Anne.kainic@va.gov

**Comment by lihanli** [comment]
@J-Quag you forgot the emails

**Comment by J-Quag** [comment]
Marino, Christopher M., PITC <Christopher.Marino2@va.gov>; 
VAVBAWAS/CO/224B <224B.VBAVACO@va.gov>; 
Alexander, Rodney, VBAVACO <rodney.alexander@va.gov>;
 McCollam, Carolyn, VBAVACO <Carolyn.McCollam@va.gov>; 
Norton, Shay, VBAVACO <shay.norton@va.gov>; 
DiTucci, Christina, VBAVACO <Christina.DiTucci@va.gov>; 
Terrell, Brandye, VBAVACO <Brandye.Terrell@va.gov>; 
Mendola, Michele, VBABUFF <michele.mendola@va.gov>;
 Lopez, Jude T., VBAVACO <jude.lopez1@va.gov>;
 Sutherland, Christopher A., VBAVACO <Christopher.Sutherland@va.gov>;
 McNeal, John T., VBAVACO <John.McNeal@va.gov>
Anne.kainic@va.gov


Sorry about that!

**Comment by lihanli** [comment]
is this in addition to the previous list or replacing the previous list?
