### ISSUE TITLE
Simplify the profile object if MVI is down or no data

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#415]
After talking with @crwallace about the possible states, seems like the profile object can / should be simplified

Below is the [current profile](vets-api/docs/api/profile.md):
If MVI is down or no vet found or multiple vets found we should convert the va_profile to an empty array.

{
  "data": {
    "id": "",
    "type": "users",
    "attributes": {
      // guaranteed not-null @ LOA 1
      "services": ["service1", "service2"], // service names TBD
      "profile": {
        // guaranteed not-null @ LOA 1
        "email": "william.ryan@gmail.com",
        // guaranteed not-null @ LOA 2 & higher
        "first_name": "WILLIAM",
        "middle_name": "P",
        "last_name": "RYAN",
        "birth_date": "1937-03-07T05:00:00.000Z",
        "loa": {
          "current": 'loa1',
          "highest": '<duplicate current if empty>'
        }
        // these are never guaranteed
        "gender": null,
        "zip": null,
        "last_signed_in": null
      }
      "va_profile": {
        "birth_date": '19800101',
        "family_name": nil,
        "gender": 'M',
        "given_names": ['WILLIAM','RYAN'],
        "status": 'active'
      }
    }
  }
}

**Comment by aub** [comment]
In Decorators::MviUserDecorator we're now swallowing the error where the user is not present in MVI, but raising it if MVI appears to be down. Is this the correct response, or should we swallow those exceptions as well? Doing so would leave the user with a degraded experience and (I think) no indication as to why that is the case, but perhaps that is better than no experience at all?

**Comment by robbiethegeek** [comment]
@aub I think the answer is to allow the user to come through and maybe think about if there is a way to message to the frontend in the profile object @crwallace, @emilyville thoughts on what you would like? Does MVI down differ in messaging from can't find user, found duplicates

**Comment by jcmeloni** [comment]
@robbiethegeek Is there more work to be done on this or is this closeable?

**Comment by robbiethegeek** [comment]
@kreek we can close this now right?
