### ISSUE TITLE
Filtering messages on same start and end date returns empty set

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-api#430]
When I search messages by the same start and end date for a date range, I get no messages back.

**Example:**
```
http://localhost:3000/v0/messaging/health/folders/-1/messages?filter[[sent_date][gteq]]=2016-11-01T00:00:00-04:00&filter[[sent_date][lteq]]=2016-11-01T00:00:00-04:00
```

**Comment by mphprogrammer** [comment]
@U-DON For the beginning date range HH:MM:SS should be 00:00:00, but for the ending date range it should be 23:59:59

**Comment by U-DON** [comment]
Yup, that was it. Totally missed that. Thanks, it's working as expected.
