### ISSUE TITLE
Nice to Haves ...

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/vets-api#434]
Creating a space where we can list the enhancements to MHV that would make code more straight-forward and eliminate workarounds.

**Comment by mphprogrammer** [comment]
1. Perform type checking when sending messages. There is an issue with MHV whereby it is possible to change the subject line of a message being replied to with a reply draft. This can occur by editing the reply draft as an ordinary draft and changing the subject line. If we then send that reply draft using the Message controller create action, the subject line of the message being replied to changes to the subject line of the (reply) draft.
2. Perform checking of replies and reply drafts to ensure that the message being replied to is permitted under MHV rules. Currently, if we send a reply or a reply draft to a message in our sent folder, MHV generates 2 messages to the clinician. We work around this by requiring the FE to filter a message thread for the last message that was received by the vet.

**Comment by ayaleloehr** [comment]
this is an excellent idea. Thanks for starting this. I will absolutely have things to add here... soon.  :)

**Comment by ayaleloehr** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/kudos-team/issues/254
