### ISSUE TITLE
Typo in API documentation

### ISSUE THREAD

**Issue by zachgoldfine44** [department-of-veterans-affairs/vets-api#4393]
## [Benefits Claims API documentation](https://developer.va.gov/explore/benefits/docs/claims?version=current) --> POST forms/2122: "Accepts 2122 **_Power of_** Power of Attorney payload".

<img width="1176" alt="Screen Shot 2020-06-16 at 10 51 38 AM" src="https://user-images.githubusercontent.com/20099764/84790673-9ca69a80-afbf-11ea-9a0c-b92b7bda0632.png">

It looks like it's coming from line 58 of https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb.

**Comment by zachgoldfine44** [comment]
@bastosmichael Let me know if I should be tagging someone else with this or submitting this in another way!

**Comment by patrickvinograd** [comment]
@zachgoldfine44 This repo doesn't house issues, generally. VFS issues go in va.gov-team, I'm not sure where Lighthouse-specific issues (of which this is one) are tracked these days.

**Comment by zachgoldfine44** [comment]
Hey, @patrickvinograd ! What a pleasant surprise :-) I hope you're doing as well as can be expected right now.

And thanks for the pointer. I'll check in with the Lighthouse team, find the appropriate place, and move accordingly.

**Comment by zachgoldfine44** [comment]
The Lighthouse team is tracking work in Jira. This issue is being picked up in this ticket: https://vajira.max.gov/browse/API-1332. Closing this issue.
