### ISSUE TITLE
Prevent LOA 3 User model validation from bubbling exceptions

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/vets-api#440]
When creating a `User` model from ID.me SAML attributes, we perform a number of validations.  For an LOA 3 user, we perform validations on certain attributes to ensure the MVI will work.  When an attribute doesn't conform to our LOA 3 User model validation we get the following...

### Current Behavior
The `/auth/saml/callback` endpoint returns an http 500 and the user gets stuck with some JSON dumped to the browser, something like:
```javascript
{"error":{"code":500,"message":"User ssn is not allowed to be blank"... 
```

### Desired Behavior
An error is logged, MVI call gets skipped, the `User.mvi.status` gets set, and the `/auth/saml/callback` endpoint returns the normal `HTTP-302`.

**Comment by jcmeloni** [comment]
Closing merged and tested issue.  @robbiethegeek  please reopen if I did this prematurely -- trying to get a clean list in front of us.
