### ISSUE TITLE
vets-api-mockdata repository not found

### ISSUE THREAD

**Issue by joejordan** [department-of-veterans-affairs/vets-api#4461]
I am attempting to set up a local instance of the VA website and api, however the [instructions](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/native.md) point me to a repo that does not exist as part of the process: https://github.com/department-of-veterans-affairs/vets-api-mockdata

Either it's now private, moved, or was taken down. Either way, I am unable to complete the setup process. Could someone point me in the right direction?

Thank you

**Comment by gunsch** [comment]
Hey @joejordan --- that repo is private and will likely remain so (linked issue has details) for people not in the `department-of-veterans-affairs` GitHub org. You should be able to still build and run the website + API without it, though I think certain kinds of functionality and testing might not work. Can you share more about your use case?

cc @johnpaulashenfelter @f1337 as FYI

**Comment by joejordan** [comment]
@gunsch I was starting work on a tech challenge and wanted to see how things worked on the site behind the scenes, specifically the form builder. I do think that some mock data would be useful in getting a fuller view of the platform.

Unfortunately I was not able to get the site to build. Hit some snags on Windows with Node running out of memory. Made a few tweaks to the process in an attempt to move things along, ultimately to no avail.

**Comment by gunsch** [comment]
Got it --- thanks for sharing, sorry to hear about you hitting those snags!

I agree that having mock data would help --- the tradeoffs for our existing data just don't work well, and we don't currently have a good way to generate/recreate that mock data either. It's something we hope to fix in the future but isn't in the cards at the moment.
