### ISSUE TITLE
MVI database down returns 200 handle as 500

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-api#450]
body will be

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <env:Fault>
      <faultcode>env:Server</faultcode>
      <faultstring>Internal Error (from server)</faultstring>
    </env:Fault>
  </env:Body>
</env:Envelope>
```

**Comment by carlmjohnson** [comment]
We have similar problems with EVSS (JSON, not XML though). See https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/error_middleware.rb for our method of catching it.

**Comment by kreek** [comment]
@carlmjohnson was heads down saw this after PR was in, this way looks better, need to investigate for middleware that parses xml (sure it must exist) so it's not parsed twice.

**Comment by austin-martinez** [comment]
@kreek we are using this to parse JSON, looks like it has an XML parser as well
https://github.com/lostisland/faraday_middleware/wiki/Parsing-responses

**Comment by kreek** [comment]
@austin-martinez thx, I'll take a look
