### ISSUE TITLE
Sign-In page & Refresh showing Sign-In page

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-api#458]
Morning,
   I'm seeing an issue with logging in and the main page not refreshing after I've completed the log in process. I have to refresh the page myself in order to see Claim Status. 
Browser: Firefox
Steps to recreate: 
1. open the link for claim status
2. click sign in (pop up appears)
3. follow the steps / 2fa
Expected results: Pop up disappears, page refreshes, and claim status summary page appears
Actual results: Pop up disappears, nothing happens on the page

I'm also seeing that sometimes when the page is refreshed within the feature, the sign in page appears for a moment then goes back to claim status.

**Comment by jcmeloni** [comment]
@crwallace Want me to xfer to vets-website and tag Vanguard?  I don't think there's anything API-related here -- but let me know if there's something you want me to run through w/ dev tools open and looking for http status codes that could be throwing things off, before you look at it.

**Comment by crwallace** [comment]
@jcmeloni -- Yes this is not an api issue.

**Comment by jcmeloni** [comment]
Moved to https://github.com/department-of-veterans-affairs/vets-website/issues/3888.
