### ISSUE TITLE
Login having CORS issues in Production

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-api#468]
Login is in production behind http auth and some CORS issues are arising.

This is the error we are seeing.

```
XMLHttpRequest cannot load https://api.vets.gov/v0/sessions/new?level=1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.vets.gov' is therefore not allowed access.
```

The response had HTTP status code 401.

**Comment by aub** [comment]
I bet this is because /sessions/new is behind basic auth but I can take a look now. We saw a similar issue before, and the CORS thing can be a red herring.

**Comment by aub** [comment]
Oh, I see. The issue is that these endpoints cannot be behind HTTP auth.
