### ISSUE TITLE
Statsd for Rx POST requests

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#476]
Can we count how many rxrefill POST requests we send via statsd?  This would let us answer the question "how many prescriptions were refilled on vets.gov"? This is where the API call actually gets made, if that's helpful: https://github.com/department-of-veterans-affairs/vets-api/blob/0b6982679b136397102f84305da133ce36072106/lib/rx/api/prescriptions.rb#L36

Ideally we will want more granular knowledge of how many of these requests are coming back with 200 responses vs 400 responses, but I think just knowing how many happen as an MVP working through statsd -> prometheus -> grafana would be a great start and let me better understand the process of setting this all up.  (hoping it's like a one line change here in vets-api). 

I have talked through this before with @aub so going to assign to him. cc @jkassemi because once we have statsd implemented we'll need to set up Prometheus to pull in the data.

**Comment by aub** [comment]
@jkassemi If you let me know what the name of the stat ought to be I can add the code to support it in no time.

**Comment by jkassemi** [comment]
Open for suggestions, but how about `api.prescriptions.refill.request.succeeded` `api.prescriptions.refill.request.failed`? `<app>-<component>-<target>-<action>-<status>`.

**Comment by ayaleloehr** [comment]
Sounds reasonable to me!

**Comment by ayaleloehr** [comment]
Closed via https://github.com/department-of-veterans-affairs/vets-api/pull/541
