### ISSUE TITLE
Contact information for ArcGIS external service integration

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-api#509]
We experienced an increased error rate from the facility locator API that triggered a PagerDuty alert. This issue appears to have resolved itself. I tracked down the ArcGIS status board (https://status.arcgis.com/), but this didn't indicate a history of problems.

Can we get documentation on who to contact in case we need support for this service during a potential outage?

**Comment by ayaleloehr** [comment]
cc @NatalieEMoore

**Comment by NatalieEMoore** [comment]
@jkassemi let me connect you with GeoBISL.

**Comment by NatalieEMoore** [comment]
can I close this @patrickvinograd @jkassemi ?

**Comment by jkassemi** [comment]
Still haven't gotten word back from Michael. I reached out again today to try to schedule a meeting.

**Comment by NatalieEMoore** [comment]
Can you join our call on Thursday and I'll add it as an agenda item?

**Comment by patrickvinograd** [comment]
At present the only insight GeoBISL team has to arcgis.com is the public status board: http://status.arcgis.com

They have a meeting scheduled sometime in the next week with either ESRI or with somebody else at VA who manages the account, and I asked them to find out if there is any additional escalation path or support contact.

**Comment by patrickvinograd** [comment]
We did not get any follow-up about escalation paths. I did document what details we have for both GeoBISL and ESRI in the appropriate location in the devops repo.
