### ISSUE TITLE
Add daily numbers to edu daily report

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-api#517]
Currently we're only showing YTD. Also include daily numbers (additional column in report).

This might affect when we send the report (currently report is sent out at 3AM right after spool file is sent). If there the SFTP server is down, retries will push out when the report gets sent. If the file fails to get sent entirely that day, the report will not be sent. 

Also add Leanna to the email.

**Comment by lihanli** [comment]
the report will run each day and give yesterday's numbers, that way it won't miss the submissions that happen after the report is run
