### ISSUE TITLE
Users middle name passed as null when it doesn't exist

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#523]
Right now vets.gov.user+264@gmail.com has a middle name of `null` as you can see below.  This user does not have a middle name in ID.me or MVI. I believe we should pass the empty string to the front end instead of `null`. Thoughts?

![screen shot 2016-11-15 at 10 17 45 am](https://cloud.githubusercontent.com/assets/4719765/20311262/1bb7b30a-ab1d-11e6-82c3-25aabbcf951f.png)

**Comment by robbiethegeek** [comment]
Looping in @crwallace is this a UI issue or an API issue?

**Comment by omgitsbillryan** [comment]
In the `empty string` vs `null` debate, I lean towards team `null`.  Returning `null` is slightly more descriptive, in that, it means the API has no data on this attribute.  `empty string` could mean it was set intentionally as an `empty string`.

**Comment by omgitsbillryan** [comment]
I tried getting the internet to tell me what to do and even _they_ seem split:
- http://softwareengineering.stackexchange.com/questions/120355/is-it-better-to-return-null-or-empty-values-from-functions-methods-where-the-ret

This could be a religious debaut but, so long as we are consistent in all our API's, I don't care very strongly either way.  That said, I still lean towards `null`.

**Comment by ayaleloehr** [comment]
Given the belief that this is a front end issue, I opened a corresponding issue in vets-website: https://github.com/department-of-veterans-affairs/vets-website/issues/4048

**Comment by kreek** [comment]
Covered by department-of-veterans-affairs/vets-website#4048
