### ISSUE TITLE
MVI retry job

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-api#532]
If the MVI request fails on login the user can still continue. Trigger a job that retries MVI _n_ times with back-off and update the MVI cache if the job succeeds.

**Comment by robbiethegeek** [comment]
@crwallace we are planning this... Please think about the way that the front end can retry if there is no va_profile

@aub anything that you can add since you are the queueing gentleman!

**Comment by aub** [comment]
It does seem like 99.9% of the complexity is on the front end here. I suspect it'll be super easy to write the job, and sidekiq will automatically retry it, but is the client going to now poll back to see if MVI data has come through?

**Comment by kreek** [comment]
Wondering if need front end logic in the first pass...
I was thinking on login we trigger an async job that, for LOA3 users, caches their MVI data. The job would only retry a couple of times. Then when the user gets to a page that requires MVI data it either has the data or it tries one more time (synchronously). Login would be faster as the MVI call is async, and services would also speed up as the MVI data is cached ready to go.

**Comment by austin-martinez** [comment]
Currently the list of services available sent to the front end depends on checking the presence of MVI attributes. How will that list be constructed if the data from MVI is fetched asynchronously?

**Comment by kreek** [comment]
@austin-martinez this will go in after the PR that gives MVI its own cache (so it can have a longer TTL than the user). Although the job is asynchronous it will run at login and cache the MVI data then. 

When the user profile is requested the user serializer would hit the MVI cache to determine the allowed services. This is similar to what happens now except the MVI data is part of the user cache. 

If a user managed to reach a service restricted page before the async job completed the new [MVI redis store model's](https://github.com/department-of-veterans-affairs/vets-api/blob/15cf6855145893bf5497688d934d6da951dbdb6c/app/models/mvi.rb#L72) cached response would be nil and it would query MVI synchronously.

**Comment by kreek** [comment]
@austin-martinez actually wait I may have lied 😁  testing this and because the user profile endpoint is returned right after the saml callback MVI will be hit (synchronously) any way, so no need to kick off a retry job unless that fails.

**Comment by kreek** [comment]
Closing this for now, will revisit if MVI triggers a breakers outage.
