### ISSUE TITLE
Ensure sensitive data will not show up in Sentry consoles

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#545]
In particular API request parameters will show up in the console by default, so ensure any of those that should not be visible are scrubbed appropriately. 

https://docs.sentry.io/learn/sensitive-data/

**Comment by patrickvinograd** [comment]
Maybe fork this off into `*-team` repos to follow up per-app.

**Comment by patrickvinograd** [comment]
Per above link this may be a Sentry config issue in which case turn this to a devops issue.

**Comment by omgitsbillryan** [comment]
@patrickvinograd  Is this still an issue?

We have whitelist log filtering within `vets-api` now: https://github.com/department-of-veterans-affairs/vets-api/commit/823284d358706d3d23d877911198186bc4bbc180

**Comment by patrickvinograd** [comment]
This was less about logs and more about things like query parameters showing up in stack traces in Sentry, but I think that has been addressed as well.
