### ISSUE TITLE
Perform Route Audit

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#551]
Please start tracking the documents

**Comment by omgitsbillryan** [comment]
@robbiethegeek can you be a little more specific? I'm not sure what kind of deliverable you're looking for. and for which routes.

**Comment by robbiethegeek** [comment]
1. rake routes
2. check the [api/docs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/docs/api) folder
3. update this issue with a table of the routes and the mappings to the markdown files there
4. Please note if there is a missing file for the route
5. Assign to @jcmeloni and @robbiethegeek
6. 🎈 🎉 🍻

**Comment by omgitsbillryan** [comment]
| Verb | Route | Doc |
|------|-------|-----|
GET    | /saml/metadata | N/A - For use by SAML SP
GET    | /auth/saml/logout | 
POST   | /auth/saml/callback | N/A - For use by SAML SP
POST   | /v0/sessions/saml_callback | N/A - For use by SAML SP
POST   | /v0/sessions/saml_slo_callback | N/A - For use by SAML SP
GET    | /v0/sessions/new | [login](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/login.md)
DELETE | /v0/sessions | [login](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/login.md)
GET    | /v0/user | [user](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/user.md)
GET    | /v0/education_benefits_claims | 
GET    | /v0/education_benefits_claims/:id | 
POST   | /v0/education_benefits_claims | [edu-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/edu-benefits.md)
GET    | /v0/disability_rating  | [disability-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/disability-benefits.md)
POST   | /v0/disability_claims/:id/request_decision | [disability-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/disability-benefits.md)
POST   | /v0/disability_claims/:disability_claim_id/documents | [disability-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/disability-benefits.md)
GET    | /v0/disability_claims | [disability-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/disability-benefits.md)
GET    | /v0/disability_claims/:id | [disability-benefits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/disability-benefits.md)
GET    | /v0/welcome |
GET    | /v0/status |
GET    | /v0/prescriptions/active | [rx-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/rx-api.md) & [prescriptions-active](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/prescriptions/prescriptions-active.md)
PATCH  | /v0/prescriptions/:id/refill | [rx-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/rx-api.md) & [prescriptions-id-refill](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/prescriptions/prescriptions-id-refill.md)
GET    | /v0/prescriptions/:prescription_id/trackings | [rx-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/rx-api.md) & [prescription_id-tracking](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/prescriptions/prescriptions-prescription_id-tracking.md)
GET    | /v0/prescriptions | [rx-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/rx-api.md) & [prescriptions](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/prescriptions/prescriptions.md)
GET    | /v0/prescriptions/:id | [rx-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/rx-api.md) & [prescriptions-id](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/prescriptions/prescriptions-id.md)
GET    | /v0/messaging/health/recipients | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/folders/:folder_id/messages | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/folders | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
POST   | /v0/messaging/health/folders | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/folders/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
DELETE | /v0/messaging/health/folders/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/messages/:id/thread | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/messages/categories | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
PATCH  | /v0/messaging/health/messages/:id/move | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
POST   | /v0/messaging/health/messages/:id/reply | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/messages/:message_id/attachments/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
POST   | /v0/messaging/health/messages | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/messaging/health/messages/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
DELETE | /v0/messaging/health/messages/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
POST   | /v0/messaging/health/message_drafts/:reply_id/replydraft | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
PUT    | /v0/messaging/health/message_drafts/:reply_id/replydraft/:draft_id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
POST   | /v0/messaging/health/message_drafts | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
PATCH  | /v0/messaging/health/message_drafts/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
PUT    | /v0/messaging/health/message_drafts/:id | [sm-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/api/sm-api.md)
GET    | /v0/facilities/va |
GET    | /v0/facilities/va/:id |
GET    | / |

**Comment by jcmeloni** [comment]
Closing this and rolling the info into https://github.com/department-of-veterans-affairs/vets.gov-team/issues/555
