### ISSUE TITLE
Create HCA Submission endpoint

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-api#580]
The route should accept a POST of JSON data at `api/v0/education_benefits_claims`, and return a success or failure message based on a call to the submission code, which will live elsewhere and can be stubbed out for this work.

Changing the url to this (from `/api/hca/v1`) will require a change on the frontend when we go live.

**Comment by akainic** [comment]
@markolson I'm assuming you mean `api/v0/health_care_application`? Is that an okay name for the route?
