### ISSUE TITLE
Construct and Send SOAP requests for HCA

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-api#582]
Existing healthcare application code makes use of a library to transform JSON data into an XML document and send it over by a SOAP request to the final endpoint. Investigate current SOAP practices in vets-api, and determine if using a library is needed.

**Comment by leannammiller** [comment]
is #660 part of this @markolson ?

**Comment by markolson** [comment]
Yes. This will be completed with 660

**Comment by leannammiller** [comment]
plus testing

**Comment by markolson** [comment]
Code has been merged. Making a new ticket for additional automated tests.
