### ISSUE TITLE
Facility Locator exception raising error

### ISSUE THREAD

**Issue by austin-martinez** [department-of-veterans-affairs/vets-api#586]
One of the error refactors broke how facility locator raises errors 
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/284/

**Comment by saneshark** [comment]
I thought I'd tested this, ughh... This one's on me. I think @patrickvinograd has a fix for this in his upcoming PR but not sure if that's ready for prime time just yet.

**Comment by patrickvinograd** [comment]
Fixed by #589
