### ISSUE TITLE
Consolidate MPI::Service and MPI::AttrService

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#6000]
It looks like we use both of these as ways to call MPI, but they are set up largely the same. Here's the prod settings: [Prod settings.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2)
Inspect the `mvi` and `mvi_hca` sections.

The only difference I could find was the `service_name` is different for both of these in the `mpi/configuration` and `mpi/attr_configuration`. 

I think we could consolidate both of these service entry points to MPI and make it a unified service

**Comment by nsoutouras** [comment]
Nick: Tech debt cleanup.  We have multiple ways of calling MPI that are redundant.
