### ISSUE TITLE
Handle nil collection data from empty response body in rx client/controller

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-api#637]
See 
    https://dsva.slack.com/archives/oncall/p1481955474000502
and 
    http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/395/

It looks like this is caused by `Common::Collections @data` being nil. Working backwards, I suspect this is caused by an empty response body from the MHV endpoint, which the json_parser middleware would do `Oj.load('')` which results in `nil`. But this is a late-night analysis so please look more carefully during daytime hours. 

Another possibility is that something about the request parameters caused the issue -  all of the requests had identical query parameters so I suspect it was a single user retrying over and over again. I don't know if they eventually gave up or if MHV started responding differently. There haven't been any prescriptions requests in the hour since then so hard to tell.

**Comment by saneshark** [comment]
I will try to recreate this and push up a patch, i think the error should have been raised in pagination but having a better error in Common::Collection would be helpful to debug as well.

**Comment by saneshark** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-api/pull/643
