### ISSUE TITLE
Throw an exception when SAML response indicates clock drift

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-api#654]
@omgitsbillryan found a number of instances of 

```
W, [2016-12-27T17:51:09.205129 #1999] WARN -- : [3d17d882-0ffa-4941-a9a0-f3ee26306d4a] SAML Response: valid?=false errors=["Current time is earlier than NotBefore condition 2016-12-27 17:51:09 UTC < 2016-12-27 17:51:13 UTC)"]
```

in the vets-api logs. These errors appear to go back to at least 2016-12-11, and were due firewall configuration errors preventing NTP server communication. These were repaired in https://github.com/department-of-veterans-affairs/devops/pull/1316.

Logging these errors to Sentry would provide more visibility in the future. The alternative is to log these as ERROR vs WARN. Open to both options, but we don't yet have alerting set up for log-based errors and our tooling around exceptions with Sentry is mature.

**Comment by omgitsbillryan** [comment]
PR Open : https://github.com/department-of-veterans-affairs/vets-api/pull/655

**Comment by jcmeloni** [comment]
@omgitsbillryan Can this be closed since the PR is merged?

**Comment by omgitsbillryan** [comment]
@jkassemi, as per [merged PR 655](https://github.com/department-of-veterans-affairs/vets-api/pull/655) we now log a Sentry message every time a login attempt fails for any reason (which includes clock drift) - does this suffice to close this issue?

I ask because in this issue, it looks like you wanted to look for clock drift _explicitly_.

**Comment by jkassemi** [comment]
Looks good, thanks! This is what I had in mind.

We'll do clock drift monitoring in https://github.com/department-of-veterans-affairs/devops/issues/1318 with associated alerts.
