### ISSUE TITLE
Set up Betamocks for MPI Gem

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#6886]
We need to make sure the MPI Gem can use the vets api mock data, and right now Betamocks is the way we probably have to do it. It's currently a middleware that we can inject with Faraday, so we either need to use a faraday wrapper, or find out how to integrate this with Savon

**Comment by lihanli** [comment]
@bosawt @bramleyjl @jimiray i think we should leave all faraday middlewares out of the mpi gem and instead allow vets-api to add middlewares to the faraday connection through a configuration block. thoughts on that?

**Comment by bosawt** [comment]
> @bosawt @bramleyjl @jimiray i think we should leave all faraday middlewares out of the mpi gem and instead allow vets-api to add middlewares to the faraday connection through a configuration block. thoughts on that?

Yeah, I was looking at the connection interfaces for the services (all the client/common SOAP stuff in vets-api), and there's a lot of stuff that we leverage that seemed like it didn't make sense to copy over. So I def am inclined to agree that we should leave the middleware in vets-api, in fact, I'm even wondering if we should rethink our boundaries in general when it comes to the connection
