### ISSUE TITLE
Investigate removing need to loa3 uplevel in certain cases

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#7397]
If we have a user who has previously logged in as loa3 successfully, and has an entry on the Accounts table, it's possible they technically don't even need to uplevel to loa3. We can at least use the Accounts table to make a call to MPI to get the relevant user information.

There are some things we'll need to consider though:
- Our assumption is that ID.me will always authenticate an LOA1 request (but with max LOA of 3) exactly the same as an LOA3 request. Is this an assumption we can reasonably make?
- An certified user will still need to log in as LOA3 at least once to get an Accounts table entry (the idea of not needing LOA3 in subsequent logins relies on leveraging the Accounts table entry)
- Is there any use case where an LOA3 user would want to be logged in as LOA1 and NOT LOA3?
- Are there legal or other implications or not logging in as LOA3 after the first time? (Again, relying on the fact that ID.me uses 2FA if you have it enabled, regardless of the requested LOA level) It is possible that we could store an extra column in the Accounts table, like `loa3_verified`, after we know the user has successfully logged in as LOA3
- Any other considerations?

**Comment by annaswims** [comment]
Another way of asking the question is "should we return PII in associated systems to non-verified people". To me, that's a quick "no".

There are many places [like this one](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/evss_policy.rb#L6) where we're checking that the veteran has all the correct id's. We're not explicitly checking that the user is LOA3, but it's inferred because we have the data that only identity-verified users have.

**Comment by bosawt** [comment]
> Another way of asking the question is "should we return PII in associated systems to non-verified people". To me, that's a quick "no".
> 
> There are many places [like this one](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/evss_policy.rb#L6) where we're checking that the veteran has all the correct id's. We're not explicitly checking that the user is LOA3, but it's inferred because we have the data that only identity-verified users have.

This isn't about returning additional PII for non-verified people, rather it's about the possibility of leveraging information we have on users who have previously authenticated with LOA3, and who are using systems that provide the same authentication for further LOA1 authentications. For example, Login.gov actually recommends logging in with LOA1 on subsequent authentications after an LOA3 auth, and using a `verified_at` field they provide to prove the user had previously authenticated with LOA3 (since the subsequent LOA1 authentications would leverage the same auth process as LOA3). ID.me appears to represent the same functionality, with the `loa highest` field being `3` proving that a user was previously authenticated with `loa3`, and subsequent logins technically being the same whether for loa1 or loa3 authentication.

Although with the paragraph above, especially with ID.me, there are assumptions there that I'm hoping to shake out with this investigation. For example, if an LOA1 authentication for a previously verified LOA3 user was actually different, then we definitely wouldn't be able to skip the LOA3 auth in that case.

**Comment by bosawt** [comment]
One consideration is that I'm not sure there's a way to perform SSO without running through the `loa3` auth loop. Eauth won't have enough information to properly save the user session if we only authenticate at `loa1`, even if we do leverage information in the `Accounts` table.

It is possible that we'd have to have to interact with EAuth in a new way, or to stop providing SSO, if we were to skip the loa3 loop

**Comment by bosawt** [comment]
I have a simple branch here that plays with this idea: `7397_investigate_removing_loa3_uplevel_in_some_cases`, there doesn't seem to be much of an issue on the backend to do this. However, I think the SSO issue is enough to table this for now.

**Comment by annaswims** [comment]
I see what you're saying, but I think that the aim (that sometimes works) is that there is one row in the `Account` table per person. Someone can have an identity-verified MHV account and a non-identity verified id.me account.  I think it may be possible that those may both be correlated with the same Account. Also, I think that multifactor authentication happens only for LOA3 logins

**Comment by annaswims** [comment]
sorry, clicked the wrong button. didn't mean to close.
