### ISSUE TITLE
Timeouts for external service integrations

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-api#74]
The DevOps team has configured monitoring for high average request latency from this application, and will work to integrate more metrics for individual services in the future. We've noticed average latency over 5 minute intervals is around ~1.5 seconds with considerable variability (up to ~40s and often between 10 and 30s).

To prevent false alarms and to better understand the application health and performance characteristics we should implement explicit timeouts around external services that this application interacts with. This also has the benefit of providing the customer a more consistent experience, since we'll be more explicitly defining the failure case and providing better feedback for things that take longer than expected or may be down.

The values for these timeouts should be based on the SLAs for the corresponding services.

**Comment by robbiethegeek** [comment]
https://github.com/department-of-veterans-affairs/platform-team/pull/146 we have started the process of how we think about this.

**Comment by jcmeloni** [comment]
@jkassemi @aub Anything left to do here?  If so, is it best to be an issue in the devops repo? (we are trying to clean up issues)

**Comment by aub** [comment]
It sounds like the implementation should be in vets-api, so let's leave it here for the moment. @jkassemi this is the first I've heard of this, but it seems doable. Are there any updates since it was originally filed?

**Comment by jkassemi** [comment]
RX, SM, MVI, EVSS, and Facility Locator services are all properly configured with timeouts. We haven't seen any requests exceed 10s in recent history, so I think we're well set here.  

None of these services provide SLAs, so it's not feasible to tie the timeout values to them.

**Comment by jcmeloni** [comment]
Closing based on @jkassemi 's comment.
