### ISSUE TITLE
Circuit breakers for external service integrations

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-api#75]
In addition to timeouts from #74 , we should evaluate implementing [circuit breakers](https://github.com/orgsync/stoplight) for each of the application's external service integrations.

Our application has the potential to send more traffic to these systems than they may expect, and if they're down or under high load, the ability to back off and allow them to recover could mean improved overall uptime for our systems.

**Comment by robbiethegeek** [comment]
@aub has started working on a Design Doc for this and will likely have a first pass at the implementation this week

**Comment by robbiethegeek** [comment]
@jkassemi is this complete? Is there anything else you need from @aub ?

**Comment by jkassemi** [comment]
@robbiethegeek - thanks, yes, breakers integration satisfies requirements
