### ISSUE TITLE
Documentation for external service integrations

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-api#76]
The DevOps team needs brief documentation around services the application integrates with so we can better configure our monitoring. This should include at least a brief description of the service, what components of the vets-api depend on that service, expected potential failures, what behaviors to expect from our app during failures, and if available, how to test the health of the service independently of application actions.

This documentation will also be useful for incident response.

**Comment by jcmeloni** [comment]
Hi @jkassemi, just making sure you still need this, or if you already have some parts of it documented elsewhere? I know DevOps has been moving fast & furious...

**Comment by jkassemi** [comment]
Thanks @jcmeloni - yep, we've started to get a good idea of what we're dealing with, but this information (and any contact information) from the folks who know the most about the integrations would still be useful.

We've only just started documenting these for ourselves here: https://github.com/department-of-veterans-affairs/devops/pull/675

**Comment by jcmeloni** [comment]
@jkassemi Anything left to do here (assuming probably so)?  If so, is it best to be an issue in the devops repo? (we are trying to clean up issues)

**Comment by jkassemi** [comment]
@jcmeloni - this is likely to be a long-standing work in progress. I'll make a note to break this out and add tickets for information we're still lacking.
