### ISSUE TITLE
Fix bug in Accounts table that prevented us from having entries with nil idme_uuid records

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#7834]
The Accounts table is currently set up to allow for either idme_uuid or sec_id to be defined, if idme_uuid is defined, sec_id does not need to be defined, and vice versa. However, we had a bug where the uniqueness constraint on idme_uuid extended to a nil definition, meaning we effectively couldn't create Account records with nil idme_uuid.

**Comment by nsoutouras** [comment]
Waiting to see how often users without an IDME UUID can log in.  May need to do further data cleanup.

**Comment by bosawt** [comment]
Am now seeing entries in the Accounts table with `idme_uuid: nil`. It looks like this can happen with mobile auth
