### ISSUE TITLE
Add log when multiple sec_ids are detected with a user's information from a SAML Response

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#7972]
Found at least one user on prod with a saved Accounts record with `sec_id='<sec_id1>,<sec_id2>'`, this has the potential to create problems on the backend, so we should at least log to see how often this happens, and potentially consider denying login when this happens

**Comment by jscanish** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7987

**Comment by nsoutouras** [comment]
Should close tomorrow when Josh returns
