### ISSUE TITLE
Refactor Account creation and querying to take into account precedence with either idme_uuid or logingov_uuid

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8016]
### **Description**
Right now, an idme_uuid match will take initial precedence over the retrieval of an Account table entry for a user, and the set of sec_id/logingov_uuid matches will return an undefined precedence over which Account table entry to retrieve. We should come up with a more sensible order of operations here and refactor these interactions in the process

### **User Story**
**As a** VA.gov user
**I want** to be able to switch credentials without losing my in-progress forms
**So that** I do not lose hours of work

### **Acceptance Criteria**

- [ ] User is able to switch from ID.me to Login.gov for the first time and not lose in-progress forms.

**Comment by joeniquette** [comment]
waiting on login.gov launch

**Comment by nsoutouras** [comment]
MSI - Blocked until Login.gov launch
