### ISSUE TITLE
Find and resolve potential Accounts table N+1 issue

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8129]
Removing the Accounts table cache, it is clear that we are querying the table too often. It is likely we have an N+1 query here, so we should find this and resolve it

**Comment by nsoutouras** [comment]
Carries forward - PR next sprint

**Comment by bosawt** [comment]
Confirmed that we are hitting the accounts table with significantly less queries after this change

**Comment by bosawt** [comment]
![Screen Shot 2021-10-29 at 11.34.00 AM.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/ab2c89eb-af98-4db0-82f0-c41286080b2b)

**Comment by bosawt** [comment]
200k queries in 24 hours where this query was running ~3 million times in 24 hours before

**Comment by nsoutouras** [comment]
Goes into VSP Identity Tech Debt
