### ISSUE TITLE
Fix slow VBADocuments Upload Submission query

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8318]
Our slowest query by far on `vets-api` is from the `vba_documents_upload_submissions` table (responsible for roughly 50% of the database pressure, according to PGHero at least). With some simple reorganization of the query and new index values, we should be able to significantly speed up the completion time of the query.

**Comment by bosawt** [comment]
- these indexes are on prod and I can see them on PGHero

**Comment by nsoutouras** [comment]
General tech debt
