### ISSUE TITLE
Hash PII info in a storable hash for us to check against for MPI consistency

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8381]
Here's how it might go:
* Initial IAL2 login from login.gov, we have eauth headers with PII
* Hash Name, Birth-date, SSN, store this in Account table or whatever analogy we're using. Mapping is now login_gov_uuid -> icn and pii_hash
* Future IAL1 logins prove they've been verified before, so we look up login_gov_uuid, retrieve icn, and make MPI call
* We hash the PII from MPI call and compare to the pii_hash value
*If it matches, user is authed at IAL2 Level
* If it does not match, user is upleveled to IAL2 through standard auth flow, we store new values for icn and pii_hash

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
