### ISSUE TITLE
As an LOA1 user, create UserVerification/UserAccount records, or retrieve existing records

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8384]
- An LOA1 user, or generally 'non-verified' user, will have a `UserVerification` record that is stored with their credential identifier (mhv_uuid, idme_uuid, etc), in addition to an associated `UserAccount` record with a `nil` value for the `icn`

- There will never be a `UserVerification` or `UserAccount` merge for an LOA1 user, so we don't have to worry about `DeprecatedUserAccount` yet

**Comment by nsoutouras** [comment]
MSI - Mostly done.  Should finish this sprint.

**Comment by bosawt** [comment]
I am seeing these being created now, seems to be working fine
