### ISSUE TITLE
Refactor Account model logic into service object

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8543]
Right now the `Account` model is overloaded with a bunch of functionality around creation (so shoved into class methods), this doesn't really make sense conceptually so we should refactor most of this logic into a separate service object

**Comment by nsoutouras** [comment]
@bosawt Does this belong in any epics like tech debt?

**Comment by bosawt** [comment]
@nsoutouras Sure, general tech debt is fine. I associated it with that epic
