### ISSUE TITLE
Move Rx API documents to vets-api

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#86]

**Comment by saneshark** [comment]
@ayaleloehr is it ok to move this into the backlog? We have some documentation already, it's just in a different repository and we could easily link to it for now if necessary. But this doesn't have the veterans-day label on it, so naturally it feels like lower priority and has been in my queue for quite some time.

**Comment by robbiethegeek** [comment]
seems like #479 is the PR for this?  Can we close this and track there?

**Comment by ayaleloehr** [comment]
Would like to leave this open until that PR is merged so it doesn't get lost or we don't accidentally think it's already complete.

**Comment by saneshark** [comment]
API docs have been moved. Closing.
