### ISSUE TITLE
Simplify SAML::User class by removing non-SSOe attribute classes

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8650]
`lib/saml/user.rb` uses a bit of a polymorphic pattern to store the `user_attributes`, but we only use one case for this now since we're 100% SSOe. It'd simplify the code dramatically to remove the unused `user_attribute` classes that aren't SSOe

**Comment by nsoutouras** [comment]
Nick: Post SSOe cleanup work.  No user impact, just cleaning up dead code.  Tech debt.
