### ISSUE TITLE
Fix bug with user_verifications being created when user_account already exists

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#8661]
There's a bug in the user_verifications logic that occurs when a user does not have a user_verification for a credential, but they have an existing user_account. It doesn't get added properly, so that needs to be resolved

**Comment by nsoutouras** [comment]
Nick: When monitoring ticket about updating acct table work, this bug was found.  No real user story at moment due to no production impact.

**Comment by bosawt** [comment]
This has been merged and in prod now. The comment from above still applies ^
