### ISSUE TITLE
Filtering for SM

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#94]
Marc and I drew this up on the board yesterday and he will provide more details on how filtering will work in the API documentation he is writing in #87

**Comment by saneshark** [comment]
`?filter[some_attribute][some_operation]=some_value&filter[same_attribute][some_other_operation]=some_other_value`

Where some_operation is one of

- eq
- not_eq
- gteq
- lteq

**Comment by saneshark** [comment]
We can add additional operations for regex matches, but those will need special sanitization so are currently not supported.

**Comment by ayaleloehr** [comment]
still to implement matches for subject line and from. 

first to push up a PR for filtering. has to fix submodule problem.
