### ISSUE TITLE
Implement Drafts for SM

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#95]
Creating and updating drafts, sending a draft, and replying with a draft.

**Comment by mphprogrammer** [comment]
- [ ] add route: POST /draft # creates a draft 
- [ ] add route: GET /draft/:id  # shows a draft
- [ ] add route" PUT /draft/:id # update a draft
- [ ] add route PATCH /draft/:id?reply_to=msg_id # sends draft as mail or reply of msg_id
- [ ] add route DELETE /draft/:id # deletes a draft

**Comment by ayaleloehr** [comment]
Can now create and update drafts. 

Marc now working on replying to drafts.  Then message replies.
