### ISSUE TITLE
Attachments for SM

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#96]
Need to implement all routes and functionality related to attachments

**Comment by ayaleloehr** [comment]
both sending a message with an attachment and retrieving attachments for messages that already have them.

**Comment by saneshark** [comment]
Going to take a stab at this on the train tomorrow. Swapping assignee. Giving @mphprogrammer my ticket for #129

**Comment by saneshark** [comment]
Got caught up on other stuff this week, but this is my current top priority unless something else comes up that needs precedence over this.

**Comment by saneshark** [comment]
Implemented and final:

GET  v0/messaging/health/messages/:message_id/attachments/:id

Implemented and incomplete (not yet ready for testing)

POST v0/messaging/health/messages
with content_type = 'multipart/form-data'

This is the same endpoint used for sending a message, but if it includes a multipart file attribute then it will save that file as an attachment. This endpoint currently works, but it will likely change. Currently it only supports sending a single attachment, it should support sending up to 4.

Not Yet implemented

Endpoint for sending a reply with attachments or creating a draft with attachments. (creating a draft with attachments does not appear to be supported by MHV, we have a call today to discuss that further).
