### ISSUE TITLE
Move healthcare_messaging gem logic to lib

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#97]
Similar to what @saneshark did here: https://github.com/department-of-veterans-affairs/vets-api/pull/88

**Comment by mphprogrammer** [comment]
[] Move Categories model/factory/spec
[] Move TriageTeam model/factory/spec
[] Move Folders model/factory/spec
[] Move Message model/factory/spec

**Comment by saneshark** [comment]
@mphprogrammer I think it's safe to maybe close this one out, right?
