### ISSUE TITLE
Generate per-region spool files

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-api#99]

**Comment by jcmeloni** [comment]
@markolson Is this something that is a requirement for Veterans Day? (I'm trying to help wrangle Veterans Day stuff into a veterans-day label for issues)  Thanks!

**Comment by jcmeloni** [comment]
@markolson Anything still to do here? (we are trying to clean up issues)

**Comment by akainic** [comment]
This is done!
